### ISSUE TITLE
Display total time

### ISSUE THREAD

**Issue by JonnyBart** [carstengehling/jirastopwatch#10]
It would be really useful to display a total of all counters. I use StopWatch to track my time for the day and then submit the times at the end of the day. A total would make it easy to check whether I have missed anything.

**Comment by carstengehling** [comment]
I can do that, but it will only be a sum all the times currently displayed in the timers. So eg. if, during the day, you have already submitted 2 hours from a timer, this will no longer show up on the total.

**Comment by carstengehling** [comment]
@JonnyBart check out the fresh new release 1.6.0 - it has what you asked for. :-)

https://github.com/carstengehling/jirastopwatch/releases/tag/1.6.0

**Comment by JonnyBart** [comment]
That's great, thanks Carsten. When small thing - when I installed the new version, I lost my settings.

**Comment by carstengehling** [comment]
Yes I know - it's because this version has changed install location. It
won't happen in subsequent versions

2016-04-11 10:59 GMT+02:00 JonnyBart <notifications@github.com>:
