### ISSUE TITLE
Auto-Adjusted Estimate is wrong if several days

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#100]
When you log time, you have the options on what to do with the remaining estimate.  Options are auto adjust, leave along, reduce by and set to, same as in Jira.

The Adjust automatically option shows what it should be adjusted to in brackets.  However, this seems to be wrong for issues with several days remaining.  E.g. logging 1 minute:
![image](https://user-images.githubusercontent.com/12972794/30645018-0d8c4400-9e1d-11e7-808b-a9acc4eb6ce6.png)
It's saying "1d 5h..." for 29.* hours  So, it seems to be treating 1 day as 24 hours.  It should instead use the value of a day from Jira, to be consistent with entered times and Jira generally.

I'll try and find time to look at this, especially since I added the remaining estimate stuff so it's probably my fault, but wanted to log an issue :)

**Comment by slarti-b** [comment]
Issue 100!  A milestone - but good or bad... :)

**Comment by carstengehling** [comment]
This is awesome Adam! Thank you very much.

Actually I think that 100 issues is a rather good milestone - especially since most of them has been closed again. It just shows, that the product is being used and evolves. 🥇 Bring out the champagne!

**Comment by slarti-b** [comment]
Definitely!  It's a useful tool and clearly being used which si great!  Thanks for it - it was just what I was looking for (well, _nearly exactly_ what I was looking for - if it was exactly what I was looking for Iw ouldn't have made any PRs :))

What are your thoughts about releasing an update with the last couple of fixes?

**Comment by carstengehling** [comment]
I'll run it on my workstation a couple of days and get the feel for it. Then I'll release it somewhere in the middle of the week. How about that?

**Comment by carstengehling** [comment]
And yeah it's getting used! I was visiting another IT company last week, a place I haven't been before. And I saw the application running on the developers workstations. So I could smile inward and think "I made that". :-) That's actually quote an awesome feeling...
