### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by ljay79** [carstengehling/jirastopwatch#102]
Hi.

I love this tool and use it now since over 1 year for my daily work and tracking with Jira.
2 things i would like to vote as a Wish.

a) support for mac. So i can have all my developers to use this tool rather than chasing them to add worklogs daily manually
b) i have to work with multiple Jira instances from time to time and i would wish i could kinda manage profiles and switch between them to use either or Jira instance

Thx a lot and checkout my Jira Add-On for Google Sheet - maybe you benefit from it like i do from your tool. [Jira Sheet Tool](https://github.com/ljay79/jira-tools/)

**Comment by carstengehling** [comment]
Hi and thanks for your kind words. Regarding your wishes:

**a) Mac support**
It should be possible using Xamarin and Visual Studio for Mac: https://docs.microsoft.com/en-us/visualstudio/mac/ I've tried it on Linux myself, and it worked for a while - then something regarding the resources.resx file messed things up.

I don't have access to a Mac, so I will not be able to try bulding it there. But feel free to make one of your developers do it, and when they get it to work, send me a pull request, so others can benefit from it.

**b) multiple Jira instances**
Not really a feature, that I will be needing myself, so it will probably go pretty low on my list of priorities. But again, if you really need it, go ahead and create it and send me a pull request.

**Comment by VladimirPal** [comment]
@ljay79 You can try another jira client - https://github.com/web-pal/chronos-timetracker it works on mac as well
