### ISSUE TITLE
FR: reminder

### ISSUE THREAD

**Issue by wolfich** [carstengehling/jirastopwatch#103]
Hi and thanks for this awesome tool!
As I've worked before with Toggl is has a feature to remind you to log your time.
What do you think about adding an option to remind one to log the time if it is working hours and no timer is running?

**Comment by carstengehling** [comment]
From the beginning, I've always tried to make Jira StopWatch as non-intrusive as possible. A reminder would be counter-productive for the way I work. But that doesn't mean that it isn't a good idea as an optional feature (read: something that can be turned on/off in the settings dialog).

Feel free to implement it, and send me a Pull Request.
