### ISSUE TITLE
Programs doesn't open

### ISSUE THREAD

**Issue by mzurita10** [carstengehling/jirastopwatch#105]
After installation in a computer with Windows 7 64-bits, the program cannot open.

I got the following error log.

```
28/11/2017 8:33:17: Unhandled UI Exception
28/11/2017 8:33:17: DPAPI was unable to decrypt data.
28/11/2017 8:33:17:    en StopWatch.DPAPI.Decrypt(Byte[] cipherTextBytes, Byte[] entropyBytes, String& description)
   en StopWatch.DPAPI.Decrypt(String cipherText, String entropy, String& description)
   en StopWatch.Settings.ReadSettings()
```

However in other PC with Windows 10 64-bit, I have not problems

How could I solve this? Thanks in advance

**Comment by carstengehling** [comment]
It's a known problem in previous version of StopWatch. I thought that I had fixed it, but maybe there is still something wrong.

May I ask: Which version did you install?

The solution:
Delete everything in this folder: C:\Users\<your-username>\AppData\Local\StopWatch\

Then when you start StopWatch again, you will need to configure it like the first time you installed the application.
