### ISSUE TITLE
Program doesn't open after Windows 10, version 1709 update

### ISSUE THREAD

**Issue by jayjaydluffy** [carstengehling/jirastopwatch#107]
Since my computer was updated to version 1709 6 days ago I can no longer get the program to run (version 2.2.0).

Are you fixing it now? Thanks

**Comment by carstengehling** [comment]
What happens when you start the program? Do you get any error messages?

**Comment by slarti-b** [comment]
Just to confirm, I'm running 2.2.0 and Windows 1709 without problem

**Comment by carstengehling** [comment]
No further data, closing.
