### ISSUE TITLE
Add sub-task support to Jira StopWatch

### ISSUE THREAD

**Issue by RisingDusk** [carstengehling/jirastopwatch#109]
My team is using Jira StopWatch right now and it's great for actually getting them to log hours in Jira, but a major downside is that sub-tasks do not show up when looking through the list for what to log hours to. Because all of our work is tracked in sub-tasks, this creates a huge issue for us and hours have to get logged to the main task instead. Is this something you could add support for given your current architecture?

**Comment by slarti-b** [comment]
You mean the auto-complete in the dropdown?  It depends on your filter - mine shows sub-tasks without a problem.  We also do our actual work on sub-tasks.

I must admit I don't sue the dropdown much - I tend to copy/paste the URL from the issue into the box but I just checked and my list includes sub-tasks

**Comment by carstengehling** [comment]
Adam is right - this is something, that you should solve in your Jira filters instead. Jira StopWatch simply asks for a list of issues based on your current selected filter - and it displays the resulting list without any preprocessing. So you could even create a filter in Jira, that eg. showed you closed issues or other people's issues. Jira StopWatch doesn't care.
