### ISSUE TITLE
Cant connect to Jira clou

### ISSUE THREAD

**Issue by danteblitz123** [carstengehling/jirastopwatch#11]
Hi there,

I am new to Jira (cloud based) and just discovered this great addon (which is perfect for us). 

I have downloaded and installed the addon on my Windows 7 machine. However when I try to connect it fails. 

I am using my Jira cloud base url, username and password. These are them same credentials I use when logging into Jira.

Is there any additional setup that I'm not aware of? e.g. granting api acess??

**Comment by carstengehling** [comment]
You need to go into settings (click on the gear icon) and setup the Base URL to your Jira server

**Comment by danteblitz123** [comment]
I already had the base url set when I tried to connect and it fails. It's the same url I use to log into Jira via my browser.

**Comment by danteblitz123** [comment]
OK figured this out, in case anyone else encounters the same issue

I was using my email address as the username, which work when I log into Jira via my web browser.

It does not work with Stopwatch though so instead I must use my actual username when using Stopwatch.

**Comment by carstengehling** [comment]
Good one - I'll make sure to mention it when I update the documentation next time.
