### ISSUE TITLE
jirastopwatch for dev teams

### ISSUE THREAD

**Issue by 8khan** [carstengehling/jirastopwatch#111]
Sorry by ask, but i have a question, its about what happen when i share an attlassian with a dev team, we can configure jirastopwatch to use the same attlasian with our own accounts?

**Comment by carstengehling** [comment]
I am not really sure, what it is that you ask me. Can you come up with an example?

**Comment by 8khan** [comment]
yeah, sorry...

well our team have an atlassian account 
http://superdev.attlasian.com/ (for example)

and we share that account in our dev team
developer1
developer2
developer3

when we try to configure the jirastopwatch with our accounts
![image](https://user-images.githubusercontent.com/3800480/34740783-379b37bc-f546-11e7-92e4-07c4faaf365e.png)

it show that on log file

Response: Unauthorized - {"errorMessages":["You are not authenticated. Authentication required to perform this operation."]

**Comment by carstengehling** [comment]
Good question. Maybe you need to use your e-mail address as username? Have a look here, see if it helps http://jirastopwatch.com/doc/#basicsetup

**Comment by 8khan** [comment]
Yeah already we test changing username by email address and the results are the same :(

**Comment by 8khan** [comment]
Sorry my bad, the configuration are with https because the jira are cloud hosted.
![image](https://user-images.githubusercontent.com/3800480/34777963-8cee517c-f5e1-11e7-884c-bd53ea4f7063.png)
