### ISSUE TITLE
Worklog : Set to function

### ISSUE THREAD

**Issue by Maikinoki** [carstengehling/jirastopwatch#115]
Hi, when I try to log work by using the "Set To" function, for example "Set To : 1h", this value is not taken into account. Only the real stopwatch value is taken into account and booked in Jira.

I also tried Reduce by and adjustments but I alwayd have same behaviour with the real stopwatch value booked in Jira.

**Comment by Maikinoki** [comment]
By debugging I think I've got part of the answer as it seems the "Set To" function just set the remaining estimate. I just found double click for editing the watch time so it's quite fine.
SOrry for wrong request.

**Comment by slarti-b** [comment]
Yes, the "adjust automatically/leave as/set to/reduce by" options are all for remaining estimate (same options as provided within Jira when logging time there".

**Comment by carstengehling** [comment]
You can read more about it here: http://jirastopwatch.com/doc/#submittingworklog
