### ISSUE TITLE
Working behind Proxy

### ISSUE THREAD

**Issue by keganonomichi** [carstengehling/jirastopwatch#116]
Hi!
Can we have proxy configuration on this application?
Thank you!

**Comment by carstengehling** [comment]
Sorry for the late answer. You are very welcome to submit a Pull Request with the feature.

**Comment by Kmaniraj** [comment]
HI,
Facing "ProxyAuthenticationRequired" error while connecting to Jira. So how to make an proxy setting here.
Thanks!.
