### ISSUE TITLE
Showing DONE issue in My OPEN issues

### ISSUE THREAD

**Issue by josepacelli** [carstengehling/jirastopwatch#120]
**Filter My OPEN issues doesn't filter DONE issues.**

![image](https://user-images.githubusercontent.com/19782727/39708010-5cf6668c-51ec-11e8-98ad-654252adbdd5.png)

Issue on JIRA
![image](https://user-images.githubusercontent.com/19782727/39708060-80688f1e-51ec-11e8-8037-5ff9e2aa899f.png)

**Comment by carstengehling** [comment]
The filters and their respective JQL is retrieved directly from the Jira API and used without any modifications. So you need to look at your filter in Jira. Maybe it is because your task is still "Unresolved"?
