### ISSUE TITLE
Saving stopwatch events to SQL database

### ISSUE THREAD

**Issue by genelewin** [carstengehling/jirastopwatch#123]
Hi there ... I am wondering if there has been any work with optionally saving stop watch events to a SQL database?  We have an custom internal time tracking solution that I would love to use stopwatch to record work start/stop and just save that to a SQL table with a Jira Key, time event (start or stop) and a timestamp.  Thank you!

**Comment by carstengehling** [comment]
Hi. No nothing of the sorts. Jira StopWatch was created to solve a specific problem: Making sure that you get your work-time registered in Jira.

You are very welcome to grab a copy of the source code, and re-use eg. the UI and time functionality to create an application, that does what you want.
