### ISSUE TITLE
Can't login with Two-Factor Authentication

### ISSUE THREAD

**Issue by DevinRaz** [carstengehling/jirastopwatch#125]
Is there existing code out there to allow login with Two-Factor Authentication enabled? 
Tested on accounts with and without two-step, Accounts with are getting the Invalid username and password Error. And without work just fine.

**Comment by 123dev** [comment]
Yep, this is an issue for us as well.

**Comment by 123dev** [comment]
Current code is authenticating using: [/rest/auth/1/session](https://github.com/carstengehling/jirastopwatch/blob/5fa092131b8a7440b27f7b441b7c72cf66b14cbf/source/StopWatch/Jira/JiraApiRequestFactory.cs#L144)` which is [deprecated](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/) and will stop working altogether on Dec 1, 2018

**Comment by carstengehling** [comment]
I've just made a release today containing API token authentication. Get it here https://github.com/carstengehling/jirastopwatch/releases/latest and try it out.
