### ISSUE TITLE
need a support on Jira Stop watch

### ISSUE THREAD

**Issue by rajeshkurumati** [carstengehling/jirastopwatch#127]
need a support on Jira Stop watch

**Comment by rajeshkurumati** [comment]
![image](https://user-images.githubusercontent.com/20907965/47523418-99482380-d85d-11e8-8eac-8d560e842d79.png)

**Comment by rajeshkurumati** [comment]
https://nuvemconsulting.atlassian.net/secure/Dashboard.jspa

![image](https://user-images.githubusercontent.com/20907965/47523491-cbf21c00-d85d-11e8-83d2-e9c65d9a3c8a.png)

**Comment by mrPsycho** [comment]
At first i thought i have same problem... 
it connects, it gets custom query.... but not issues...

so i think this is because of new version, which is not work with this release. 
and cause there is no maintainer... so it won't work for some time.
