### ISSUE TITLE
Jira Stopwatch will not open

### ISSUE THREAD

**Issue by Manie-Verster** [carstengehling/jirastopwatch#128]
I have the below issue with starting my Jira Stopwatch and send an e-mail a month ago and again today to the e-mail address given. Please help.

![image](https://user-images.githubusercontent.com/44962101/48332568-0846ba00-e65d-11e8-99d6-5509ca99cacd.png)
By the way I did delete all the subfolders under the Stopwatch folder as given in the message and still no joy.

**Comment by carstengehling** [comment]
I've replied to your email, hope this helps.
