### ISSUE TITLE
Minimse crashes StopWatch

### ISSUE THREAD

**Issue by hr-m** [carstengehling/jirastopwatch#13]
Clicking on Minimise button will crash the application.
At first it appears that application just closed, as if Exit button has been clicked, but actually it crashed.  
If any settings were changed they will not be saved.

**Comment by carstengehling** [comment]
Nice spotted - it actually is still running, but is hidden instead of minimised. This should only happen when checking the option "Minimize to systemtray"

**Comment by hr-m** [comment]
I see -- I missed that it goes into the tray.  I just noticed I have a few of them running at the same time, which probably explains why settings were not saved if you save on exit.  Maybe the problem goes away if you restrict to just one running instance?

**Comment by carstengehling** [comment]
Well there _is_ a bug. The usecase when clicking the minimize button should be:

1) "Minimize to tray" is checked => the window is hidden and an icon is shown in system tray
2) "Minimize to tray" is not checked => just minimize normally to taskbar

What really happens in 2) is that the window is hidden instead of minimized. So I'll make a bugfix on this.

**Comment by carstengehling** [comment]
Fixed in 1.7.0 - check the pre-release: https://github.com/carstengehling/jirastopwatch/releases/tag/1.7.0-pre1

**Comment by hr-m** [comment]
Minimizing to tray/taskbar seems OK now.  Except I really got confused initially as it looked like StopWatch disappeared after minimizing to tray due to dark gray default colour of the taskbar on Windows 10 which seems to exactly match the colour of StopWatch icon.  Consider adding an outline around the icon.

Before I discovered the problem with 'invisible' icon I got confused even more as it looked like switching from minimizing to tray to minimizing to taskbar crashes StopWatch and wipes all setup.  Turned out setup is fine but multiple copies of StopWatch can be started that do not share the setup (how does that work?).  This is very confusing.  Pleas consider limiting to just one running instance.

**Comment by carstengehling** [comment]
Good point about running only one instance. 

I haven't tried using Windows 10 yet, so I have not seen how it looks with the dark theme. I'll look into it.

**Comment by carstengehling** [comment]
I've implemented the "single instance" feature in latest pre-release: https://github.com/carstengehling/jirastopwatch/releases

**Comment by carstengehling** [comment]
I've found a new icon, that looks okay on both Windows 7, 8 and 10 :-)

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases

**Comment by hr-m** [comment]
Only single instance running now.
Good icon!

**Comment by carstengehling** [comment]
Thank you :-)
