### ISSUE TITLE
Jirastopwatch dont add times to jira

### ISSUE THREAD

**Issue by 8khan** [carstengehling/jirastopwatch#136]
From 18-03-2019, Jirastopwatch show "connected" status, but at send time logs to jira that didnt appear on the calendar/timelog :(

**Comment by bluish5** [comment]
I'm experiencing the same issue. It seems to create the worklog, but on JIRA it is not present. I don't know if this issue is connected with Tempo plugin that we use in JIRA.

**Comment by 8khan** [comment]
I thing so, maybe the connection api changed

**Comment by camilazoly** [comment]
Same thing here...

**Comment by carlclark267ds** [comment]
We are experiencing the same issue.   My investigation showed that Jira Stopwatch was passing the worklog entry to Jira.  You can call Jira's API and retrieve the worklog entry successfully (accessing the Jira API directly) after posting a worklog entry from Stopwatch

I have submitted a Jira request - https://getsupport.atlassian.com/servicedesk/customer/portal/23/JST-460905.

@8khan thanks for the Tempo tracker reminder. I think we may revert to that in the interim.

**Comment by carlclark267ds** [comment]
Hi All, 

This looks to be a Tempo issue not a Jira issue.  This History tab in Jira is showing the worklog recording, however it is not reflecting in Tempo.

**Comment by bluish5** [comment]
I have the same opinion. I opened an issue on Tempo support: https://tempo-io.atlassian.net/servicedesk/customer/portal/6/TCS-9001.

**Comment by bluish5** [comment]
Tempo replied me:

> Thank you for reaching out to us.
> I can confirm that there was a bug with the sync of worklogs from JIRA to Tempo.
> A fix for this was released earlier today and the worklogs should now be synced correctly. This sync might take some time ( depending on the number of worklogs that need to be syced).
> Can you please check later today and confirm that the worklogs are showing in the Tempo views.

I can confirm that in our case the problem is gone and also "hidden" worklogs are now visible in Tempo.
I hope it is solved for anybody else!

**Comment by 8khan** [comment]
Thanks @carlclark267ds @bluish5 
today when I logged on tempo (jira) noticed that some timelogs appear duplicated but thats because y logged manually some times
Actually Jirastopwatch are running without problems 💯

**Comment by carlclark267ds** [comment]
Tempo replied to me too and we are backup and running.  Thanks for the input everyone.
