### ISSUE TITLE
Time slot JIRA combo box strange update behaviour

### ISSUE THREAD

**Issue by hr-m** [carstengehling/jirastopwatch#14]
If filter is not used, combo box does not update automatically when JIRA issue entered -- none of pressing enter/return, opening a list or waiting works.  The only way to update the time slot seems to be to be on field exit, which is a very strange mode of operation for a combo box.

**Comment by carstengehling** [comment]
You are right - I'll fix this behavior.

**Comment by carstengehling** [comment]
This has been fixed in 1.7.0 - check out the pre-release:

https://github.com/carstengehling/jirastopwatch/releases/tag/1.7.0-pre1

**Comment by hr-m** [comment]
If I type in a correct JIRA issue and press Enter the summary gets updated -- nice.

However, this field will now throw an exception if I try to open drop down list, regardless of whether field contains a valid JIRA issue or not.  Whether I have filter set or not set does not appear to make any difference.  Is filter searching now broken?

**Comment by carstengehling** [comment]
That is strange indeed, I will have a look

**Comment by carstengehling** [comment]
An omission by me when making the scrollbar feature. It's now been fixed

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases

**Comment by hr-m** [comment]
Exception issue fixed.
