### ISSUE TITLE
Could not Connect to local Jira withOut API Token 

### ISSUE THREAD

**Issue by icelaser** [carstengehling/jirastopwatch#141]
With the new Version 2.3.0 can you use the API Token for https://id.atlassian.com/login?continue=http://id.atlassian.com/manage/api-tokens
but local Jira Server could not Connect with API Token.
Can you insert a Seccond Login with Password?

![image](https://user-images.githubusercontent.com/33600531/57278253-4e2d8980-70a6-11e9-88a0-3e02975ca430.png)

![image](https://user-images.githubusercontent.com/33600531/57278292-643b4a00-70a6-11e9-92c6-237690628b96.png)

**Comment by jacenat** [comment]
Ran into the same issue after updating. As per https://community.atlassian.com/t5/Jira-questions/Re-Re-Create-API-token-for-a-user-in-Jira-Server-Locally/qaq-p/918450/comment-id/294524#M294524 basic auth seems to be depricated in the cloud. Maybe Carsten works mostly with cloud?

In the meantime I'll switch back to a previous version.

**Comment by carstengehling** [comment]
Could you try to just write your normal password in the "API Token" field? Someone else tested that on a local Jira install, and reported that it worked. If this is also the case for you, I'll make sure to reword the label next to the field.

**Comment by Falco20019** [comment]
I can confirm that using the password in the API Token field still works with Jira 6.4.12 Server. I had to logout on the webpage and enter the catcha first since I changed my password recently and JIRA Stopwatch 2.2.0 tried it until it got blocked with the old password before updating.

**Comment by jonathan-niven** [comment]
Would it be possible to allow support for both API token and password authentication, allowing a user to select which they'd like to use?

**Comment by carstengehling** [comment]
Yes it would be possible. But as stated on the README, I don't really have the time to work on Jira StopWatch anymore and am looking for someone who wants to take over. If you can make a pull-request, that bakes in dual-support, I'll be happy to release it.

Another workaround would be to download version 2.1.0. Only difference between 2.1.0 and 2.2.0 is the authentication scheme.

**Comment by icelaser** [comment]
I tried it again. But the same problem. Now i will never updated again. I think it has to do with the oauth version. Version 2.2 uses ../rest/auth/1/session and version 2.3 uses ../rest/auth/2/session
It is also strange that my password was somehow wrong.

**Comment by icelaser** [comment]
Now, i have a Solution for the Problem. Before you install the New Version, you must delete the Settings: URL, User and Password.
After that, you can Install the new Version. Start the new JiraStopWatch Version and go into the Settings. Add the URL, User and Password and it work.
I think it was because of the password, which was encrypted with the new version.
