### ISSUE TITLE
No Seconds in timer

### ISSUE THREAD

**Issue by houssein-moussawi** [carstengehling/jirastopwatch#142]
Hi 

Can we add a feature so that seconds are shown in timer and not just minutes and hours.

Thank you

**Comment by carstengehling** [comment]
Hi Houssein,

Leaving out seconds was an active choice from the beginning, when I created Jira StopWatch, for a couple of reasons:

1. I created (and used) the stopwatch for measuring time spent on coding tasks, debugging, brain-storming and such. And I believe work like that does not benefit from being measured in any lower granularity than minutes.
2. If the stopwatch is visible on the screen, I would find it quite stressful to see the seconds ticking away, while working. It would turn out to be counter-productive.

That being said, why would you like seconds to be shown as well?

**Comment by houssein-moussawi** [comment]
Hi Carsten

I understand your point of view.

actually its psychological, I am having a hard time to seeing if the timer is on especially when I am working in more than one project on the same day so its easier with seconds.

I actually minimize the timer when working and do not keep it on the screen but when my OCD kicks in and I need to check if the timer in ON or check for time its easier will seconds.

It would be great if we can add the seconds.

Thank you.


________________________________

**Comment by carstengehling** [comment]
You already have a visual feedback for that. If a timer is running, the background color on the time field is green:

![image](https://user-images.githubusercontent.com/54675/59747044-62090580-9278-11e9-9c7f-43a952ebbbf7.png)

So if it is only for this reason, the drawbacks definitely outweighs the benefits.

**Comment by houssein-moussawi** [comment]
Thank you for your time carsten and for the great application.

Regards


-------- Original message --------
