### ISSUE TITLE
Time field doesn't work very well

### ISSUE THREAD

**Issue by hr-m** [carstengehling/jirastopwatch#15]
1. Attempting to enter something like '6h 20m' doesn't work very well -- after entering '6h' part have to move cursor to minutes otherwise '6' gets overwritten with '2'.  What is the point of automatic expansion after 'h' to add minutes if cursor isn't automatically moved?  Would be better if field did nothing, much easier to just let me type in the whole '6h 20m' string.

2. Attempted to add manual update '1d' through Stopwatch -- this does not enable 'Submit' button.

**Comment by carstengehling** [comment]
I agree. Inplace editing inside the time textbox doesn't work very well as it is now

re 1: The thing is, the application needs to parse the input at some point. It can either happen as you type (current implementation) or when you shift focus away from the textfield. In the latter option, you would then have the problem, that the timer would not know when you are finished unless you leave the textfield. So if you don't, then the running timer cannot update the field. I am thinking about doing the editing in a seperate dialogbox, which would fix all catch-22 issues.

re 2: Yes currently the application only parses hours and minutes. I didn't think anyone would track for more than 24 hours before submitting a worklog. But that is easily fixed, and I will do that in a future update.

Thanks for your issues :-) It helps making the app better.

**Comment by hr-m** [comment]
Why do you want to parse it?  Wouldn't it be simpler if you just provided two (or three) boxes, for days/hours/minutes, that user can tab between?  A bit old school but easy to navigate and easy to validate.

**Comment by carstengehling** [comment]
Mainly to keep with the functionality that is used in Jira itself. Also parsing isn't the problem, it's _when_ to parse, that has been the pain. Which will be fixed by doing it in a separate modal-box.

**Comment by carstengehling** [comment]
The pre-release of 1.7.0,, that I've just made, fixes this in an IMHO elegant way. The setting for making the timer field editable is gone - that field is now always read-only. BUT if you double-click the field, you will get a dialog where you can edit the time unobtrusively.

https://github.com/carstengehling/jirastopwatch/releases/tag/1.7.0-pre1

This solves the issue. Let me know what you think about it.

**Comment by hr-m** [comment]
Can't say I'm a fan of the new behaviour.

- I have two monitor setup.  I had StopWatch is on my main monitor and did the double click on the timer field -- the new dialogue opened on the other monitor;
- On Windows 10 it's very hard to move the dialogue as there is very little space on the title bar to grab -- it's covered by buttons;
- You can stretch the window but dialogue doesn't really resize.

I'd attach screenshots but don't see a way to do it.

Furthermore, parsing is still buggy.
- It accepts up to '23h 59m'.  I'd like to see days, but fine.  At least if I add something like '2d' I get red field background.  But if I enter '24h' or more, this is accepted but time field is set to '0m'.
- Parsing gets confused if there is no space between hours and minutes.  E.g. '23h59m' (note no space) is interpreted as '22h 19m'.

**Comment by carstengehling** [comment]
My bad. The dialogbox should of course appear directly on top of the main window, just like all the others. I'll get that fixed. 

And I'll give the parsing some more love. :-)

**Comment by carstengehling** [comment]
I've just uploaded a new pre-release, that fixes these issues + the problem regarding the combobox. Give it a spin.

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases

**Comment by hr-m** [comment]
Works well now.
