### ISSUE TITLE
Can't connect to JIRA if browser gives certificate warning

### ISSUE THREAD

**Issue by hr-m** [carstengehling/jirastopwatch#16]
Our internal test JIRA server uses self-signed certificate which seems to prevent StopWatch from logging in.

**Comment by carstengehling** [comment]
That's outside of StopWatch scope. Either get a signed certificate OR run without SSL (http:// instead of https://). If it is an internal test server, you shouldn't need SSL?

**Comment by hr-m** [comment]
I haven't explained the problem well.

Running a test server with self-signed certificate is not unusual.  I don't think having to change the way JIRA test server is run (i.e. having to get and install a CA-signed certificate or running without SSL) in order to test a convenience utility is something most people are likely to do, regardless how good it is, because they usually have a reason (good or bad) for setting up their test server in a particular way.

When StopWatch attempts to connect, it just fails silently with no explanation -- all you get is "not connected".  At this point it looks like StopWatch isn't working at all -- time to try some else from Jira Marketplace.  The only way to find out that StopWatch does work is to connect to a JIRA server with CA-signed certificate -- and if the only one available is the production server then not everyone would risk it.  Even if you don't want to handle this then shouldn't StopWatch at least clearly state what the problem is?

**Comment by carstengehling** [comment]
Good point. I try to make the UI as unobtrusive as possible, so having a dialog popping up with error messages isn't really my thing. But I could make the "Not connected" clickable and make that click popup the error message.

**Comment by hr-m** [comment]
Thanks!

**Comment by carstengehling** [comment]
You're welcome - best improvements always come from user input. :-)

**Comment by Falco20019** [comment]
For me the tool works great with our self-signed certificate. Was this fixed? Otherwise, maybe you only have to trust the certificate in windows for the tool to work.

**Comment by carstengehling** [comment]
No it wasn't fixed. I need to propagate the actual connection error from deep in my Jira api-layer up to the UI - that doesn't happen ATM.

**Comment by wackywalt** [comment]
Sometimes the JIRA login requires a CAPTCHA. This could mislead one into thinking that Stopwatch is broken, but it is not. Just logout of JIRA from your web browser, and log back in. This will trigger the CAPTCHA request. Once you successfully log back in, Stopwatch will be off and running again.

I noticed version 1.7 no longer has the ability to edit the timers.

**Comment by carstengehling** [comment]
Yes I am working on that part. Some of it will be actual HTTP errors and some will be messages from Jira API - I'll try to unify the user-feedback regardless of the source of error.

**Comment by carstengehling** [comment]
This feature will be part of the 1.9.0 release, that is ready within a week.
