### ISSUE TITLE
No chance to edit the config if you use 20 issue fields

### ISSUE THREAD

**Issue by Halpha** [carstengehling/jirastopwatch#17]
I just thought it would be a good idea to choose 20 issues in the config "issueControls displayed". Then I had a windows larger then my screen, so I thought, nice I just scroll down, but this is not possible. So I tryed to change the config file in the install folder, did not work.. I changed my screen to portrait, no chance to see the config at the ground of the window. Uninstall does not remove the config so I had finaly to remove the regestry entries I found and then I was able with a different install dir to change the config...

Please change it:(

**Comment by carstengehling** [comment]
Have you tried to press ALT-SPACE to open the standard window menu, then select "Move" and use arrow-keys to move the window up, until you can see the settings icon. Now you can click on it and change the number of issues.

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases

It addresses this issue
