### ISSUE TITLE
Recorded time lost if StopWatch closed

### ISSUE THREAD

**Issue by hr-m** [carstengehling/jirastopwatch#18]
If I click on the close button Stopwatch will close immediately, without a warning.  Since there was no warning I expected recorded time to be saved and restored on restart, but it wasn't.

Recorded time should really be backed up somewhere occasionally.  Any crash or reboot will cause a data loss, and now with forced Windows updates these happen relatively frequently.

**Comment by carstengehling** [comment]
Try to click on the settings icon (gears icon) in the lower right corner. THen have a look at the setting: "Save timer states on program exit".

Stopwatch can save your recorded time, as you requested. It can even keep the timer "running", if eg. you need to reboot your machine, but still wants to record time.

**Comment by hr-m** [comment]
I missed that.

**Comment by hr-m** [comment]
My PC blue-screened while I was working.  Upon reboot all times were reset.

**Comment by carstengehling** [comment]
Currently settings and timers are only saved on normal program exit. I don't know, why I didn't think of crashes, but thanks for mentioning it. I'll make a fix in the near future.
