### ISSUE TITLE
Submit worklog issue

### ISSUE THREAD

**Issue by hr-m** [carstengehling/jirastopwatch#19]
I'm not sure if this issue is due to StopWatch, JIRA or both.

Yesterday I used "Submit worklog to JIRA" button to update time spend on new JIRA.  The worklog dialog popped up, I clicked Submit and nothing happened -- JIRA was not updated.  There were no connectivity issues, JIRA was working fine, StopWatch was showing that it is connected, if I added another JIRA to StopWatch it seemed to work.  I repeated the process twice more, waiting several minutes after each attempt, but JIRA was not getting updated.  Eventually I gave up and updated JIRA manually by modifying the remaining time.

Today I used StopWatch again for the same JIRA.  When I submitted time today it worked -- but the time worked yesterday was removed (there was no worklog entry for it, I updated time remaining directly by editing JIRA).

I don't know if this is something you want to handle but even if not maybe it warrants an entry in FAQ/Help.

**Comment by carstengehling** [comment]
Yeah I've noticed this myself. What happens is, that if kept idle for some time, Jira API will expire the authentication. If that is the case when sending a request. Stopwatch will do a re-login, and re-send the original request.

But I found out last week, that even though Jira API reports "ok" for the login, there is a little delay, before Stopwatch can resend the request. I haven't had time to implement this yet, but it will come soon.

**Comment by carstengehling** [comment]
Have a look at the pre-release of 1.7.0, that I've just made.

https://github.com/carstengehling/jirastopwatch/releases/tag/1.7.0-pre1

This solves the issue. Let me know what you think about it.

**Comment by KrisMuree** [comment]
Hi,
  I try to use stop watch, but the comments are not updating in the server? Will this get fixed? Also, can we use your app in mac world?

Thanks,
Kris

**Comment by carstengehling** [comment]
In the settings you can configure how you want the comment posted: as a comment, as part of worklog, or both. 

Regarding Mac: you should be able to compile the source using the Mono libraries 
Danielleeds have done so succesfully, see this issue https://github.com/carstengehling/jirastopwatch/issues/6

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases

**Comment by hr-m** [comment]
I haven't noticed any further issues with missed worklog updates.
