### ISSUE TITLE
Timer increment works with field value

### ISSUE THREAD

**Issue by sfeldkamp** [carstengehling/jirastopwatch#2]
As a user, I sometimes (often) forget to start the timer when I actually start a new task.  I would like to be able to enter some time manually into the field, then click the start task button and have it begin incrementing from the time that I entered.

Workflow:
* I start working on a new task.
* 5 minutes later I remember that I haven't started the task in JIRA StopWatch
* I enter "5m" for the task and click Start button
* I click the Start button for the task keeps the "5m" I set the task to be
* 1 minute later Jira StopWatch increments the time to 6m

This should also work for tasks already in progress.  E.g.
* I click the Start button for the task
* 5 minutes later I remember that I actually started on it 20 minutes ago
* I enter "20m" in the field for the task
* 1 minute later Jira StopWatch increments the time to 21m

**Comment by carstengehling** [comment]
Haha nice one - that's also something that I often forget. :-)

And it actually shouldn't be too hard to implement - I just need to do a parser for the Jira time format. I'll look into this. Thanks for the suggestion.

**Comment by carstengehling** [comment]
I've made a test-version which resolves this request. https://github.com/carstengehling/jirastopwatch/releases/tag/1.4.0-pre1

No setup program - just unzip the files into the folder where JiraStopWatch is installed. You may want to backup the originals first. Also when starting the program you might be asked to re-configure the program (Jira URL, etc).

The feature can be enabled in the settings-dialog. Try it out and let me know if it works as expected.

**Comment by sfeldkamp** [comment]
It's working!  I'll use it today and let you know if I run into any problems with it.  Thanks again!

**Comment by sfeldkamp** [comment]
Noticed an issue with this.  JIRA supports decimals in their worklog times.  1.25h == 1h 15m.  1.25h is instead rounded down to 1h 0m by Jira Stopwatch.

Not a big deal, just something I noticed.

**Comment by carstengehling** [comment]
Yeah I've only implemented the "2h 45m" format, since it's also the one that I use for displaying the time. IMHO this is actually a much nicer way to display/input times, since you don't have to do the rounding math in your head. But I could add the decimal support, if you really care for it.

**Comment by sfeldkamp** [comment]
I'm sure I'll be able to adjust to it.  We have a policy of rounding our
time to the nearest quarter hour.  So that's why I ended up tracking it in
decimal format.
