### ISSUE TITLE
20 Timers Hides Settings and Jira Connection Info

### ISSUE THREAD

**Issue by matthewdenison** [carstengehling/jirastopwatch#21]
I turned on 20 timers and lost the settings icon so I can't get into settings anymore. A reinstall didn't help. Maybe it would be better to put the timers in a scrolling list and make the window resizable so that I can always have access to the settings icon.

**Comment by matthewdenison** [comment]
Workaround was to change a display to portrait mode and then I was able to get back to settings.

**Comment by carstengehling** [comment]
You're not the only one who's discovered this problem. :-) I'll do something with a scrollbar, if the number of issue slots makes the window too high.

**Comment by carstengehling** [comment]
Have a look at the pre-release of 1.7.0, that I've just made.

https://github.com/carstengehling/jirastopwatch/releases/tag/1.7.0-pre1

This solves the issue. Let me know what you think about it.

**Comment by matthewdenison** [comment]
Hi Carsten,

 

Great news! :)

 

I tried to download it but there are only source downloads – do you have an installer I can try out?

 

Matthew

**Comment by carstengehling** [comment]
It's because I've already released 2 new pre's afterwards. I should have sent you this link instead which just shows latest release in the top: https://github.com/carstengehling/jirastopwatch/releases

**Comment by matthewdenison** [comment]
Perfect! Works great on my side so far.

**Comment by matthewdenison** [comment]
Just noticed something. Can’t manually modify times.

**Comment by matthewdenison** [comment]
Nevermind, double clicking works!

**Comment by carstengehling** [comment]
Yes the time edit feature has been radically changed due to https://github.com/carstengehling/jirastopwatch/issues/15

I will of course make sure that this is described in the release notes. :-)

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases
