### ISSUE TITLE
Unable to resize

### ISSUE THREAD

**Issue by Gazvenn** [carstengehling/jirastopwatch#22]
I set the maximum issues to 20 which resulted in them needing more room than full screen height. the window has got stuck at screen height which only has room for 18 issues and has pushed the settings button outside the window view with no ability to resize.

**Comment by carstengehling** [comment]
This has already been fixed in the pre-release of 1.7.0, that you can download from here:
https://github.com/carstengehling/jirastopwatch/releases

The final release will come out within the next days.

**Comment by carstengehling** [comment]
For more info: https://github.com/carstengehling/jirastopwatch/issues/21

**Comment by Gazvenn** [comment]
Thanks for pointing out changes. I had to reinstall to resolve the original issue and found your latest version and just tested again and all good. Really appreciating the quick reply on both issues as well.

**Comment by carstengehling** [comment]
You are welcome. All new features and bugfixes will of course be added to the README file, when I release.

**Comment by carstengehling** [comment]
Final release of 1.7.0 now available: https://github.com/carstengehling/jirastopwatch/releases
