### ISSUE TITLE
Issues selection

### ISSUE THREAD

**Issue by Gazvenn** [carstengehling/jirastopwatch#23]
Only seems to load the results from the equivalent of the first page of a filter when looking through JIRA.

**Comment by carstengehling** [comment]
StopWatch loads whatever the Jira API returns from the particular filter.

**Comment by carstengehling** [comment]
I just looked at the API, and it _does_ support pagination. So I might be able to do something there. But it will not be for this release, since it is already overdue.

**Comment by carstengehling** [comment]
This has now been added with the query-parameter maxResults. I've set it to 200, which ought to be enough. Please note though, that this can be overrided by Jira settings, as per Jira API documentation:

_the maximum number of issues to return (defaults to 50). The maximum allowable value is dictated by the JIRA property 'jira.search.views.default.max'. If you specify a value that is higher than this number, your search results will be truncated._

This will be available in the next release.
