### ISSUE TITLE
Editing Times behaviour

### ISSUE THREAD

**Issue by evladutoiu** [carstengehling/jirastopwatch#24]
Hi Carsten,
Don't want to be nitpicking but, i love the way you've made the pop-up for editing times on double click. 
My issue with it, is that when running, if I want to dynamically edit the time, when opening the pop-up, it gives me the last saved value of the time (from he last pause) instead of the currently displayed time. 

Thus I need to pull the pop-up window aside and manually write in the running value.
Hope this makes sense. I can provide more info if needed!

Really helpful app man! Thank you!

**Comment by carstengehling** [comment]
Thank you for the kind words. The Edit dialog should be presenting the actual time displayed in the box, that you double clicked on. Could you please elaborate on, what you experience?

**Comment by evladutoiu** [comment]
I've attached two pics. Hope they work.
Basically, I started my time at 5m. I left it to run until 16m. While still
running I double click the running time and it shows me the last saved time
(5m) even though it should show me 16m. Does that make sense?


[image: Inline image 2][image: Inline image 1]


--
Manu Vladutoiu

**Comment by carstengehling** [comment]
Yes that is not the way it should work. Have you downloaded the pre-release or the final release? Because the pre-release had this bug.

**Comment by evladutoiu** [comment]
my bad for not trying the final release! Works perfectly!
Also, really appreciate the icon change! I am using a dark theme on windows and could never actually tell where the icon was in the taskbar!

You can close this and mark it as super done!

**Comment by carstengehling** [comment]
You were not the only one, regarding the icon. I've only used Windows 7 and 8,so hadn't noticed it myself.
