### ISSUE TITLE
Trivial: Taskbar icon randomly mis-renders

### ISSUE THREAD

**Issue by denglish14** [carstengehling/jirastopwatch#29]
I haven't been able to pinpoint why, but sometimes the taskbar icon for the stopwatch renders in a weird way (see attached screenshot). I've seen this behavior on multiple machines (all running Windows 10). Sometimes it looks fine. Sometimes pieces of it go missing. Which pieces go missing also seems to be random.
![taskbar screenshot](https://cloud.githubusercontent.com/assets/1658390/17894496/92f053b6-6917-11e6-9b37-cac73d58e24a.png)

EDIT: It also doesn't seem to matter if I kill the app and reopen it. It just reopens with whatever rendering was last there.

**Comment by denglish14** [comment]
FWIW, I just realized this may be related to a busted Windows icon cache. I just tried rebuilding it and so far the icon looks OK. I'll revert back if I see it get out of whack again.

**Comment by ProsperoTheBun** [comment]
I recognise that this is trivial but I still think this should be reopened and fixed.
If I am running Jira StopWatch and also, say, presenting a demo, it doesn't inspire confidence when there is a broken icon on the taskbar.
I may fork this and attempt to fix it - I'll let you know how I get on.

**Comment by davin-english** [comment]
@ProsperoTheBun I actually fixed it myself by going to the same website for icons that this repository uses and then I used a different service to convert to .ico. I think whatever was originally used to do the conversion is the problem. I didn't contribute the fix though, because I have no idea if I violated any copyright/license agreements by using that conversion service.

**Comment by tgourley** [comment]
For me, the icon is fine until I "pin" it to the Windows taskbar.  Strange.

![image](https://user-images.githubusercontent.com/495655/57314263-4fb77b80-70bf-11e9-9127-14b732dc196b.png)

![image](https://user-images.githubusercontent.com/495655/57314229-39112480-70bf-11e9-8181-6d587f4c232d.png)

![image](https://user-images.githubusercontent.com/495655/57314249-475f4080-70bf-11e9-9b25-a9f749be8af1.png)
