### ISSUE TITLE
Add a way to add worklog comments before pushing to JIRA

### ISSUE THREAD

**Issue by sfeldkamp** [carstengehling/jirastopwatch#3]
I often switch back and forth between tasks during the day.  I don't want to push my time to JIRA every time I task switch because then I'll lose context for my day.  Having a way to add comments about the worklog without pushing the time to JIRA would be very handy.  It would especially would be nice to be able to see those comments in the interface.

Proposed Solution:
* Add a field for comments to each task on it's own row, below all the existing buttons and fields
* Add a button to each task to toggle shown/hidden the comments field for each task
* Save the content of the comments field as it changes

**Comment by carstengehling** [comment]
First of all: Why is it, that you don't want to just submit the time + comment at every switch? Is it because you want to see the total distribution of the days work before submitting?

The tricky part here is, that the issue keys are actually very loosely coupled to the timer. You can actually start a timer and postpone writing the issue key until you want to submit. So if I made this change, the comments would be bound to the timer - the row as you also describes.

Second question just to clarify: Do you simply want these partial comments to be concatenated and then pushed all as one comment when submitting the worklog?

I'm very cautious with cluttering the main UI screen too much. How would it work for you, if this functionality was added to the "submit worklog" window? So that there can write the comment, and instead of posting, you click on another button to save the comment. Also here showing all the previous comments.

**Comment by sfeldkamp** [comment]
Yes, I want to submit just one worklog for each JIRA ticket per day.  The reason for that is that I have to enter my time into two systems, JIRA and also an older custom system that our payroll department still uses.  The easiest way for me to do that is to just have one JIRA worklog per ticket per day, then I can copy and paste that into the other system.  Also, it's just nice to have a view of how my day has gone.

Your suggested solution sounds much nicer.  That would work very well for me.

Thank you for making this tool.  If I can help with testing or anything else please let me know.

**Comment by carstengehling** [comment]
I'll see if i get time to do both issues during the holidays, and then do a pre-release that you can test.

You are very welcome - the idea for the tool simply came out of a personal need to do this kind of time-tracking. Spread the word to your colleagues and others. The more people who're using it, the happier I get. :-)

**Comment by carstengehling** [comment]
Try this out: https://github.com/carstengehling/jirastopwatch/releases/tag/1.4.0-pre2

I've tried to keep it simple by simply concatenating the comments and tagged each with a timestamp. At the end they would need to be submitted as one string to Jira anyway. Hope this sits well with you.

Also I've enhanced the UI of the "post worklog" button a bit. When you save a comment for later use, the icon will have an exclamation mark added to indicate, that there are unsaved comments.

As before, just unzip the files into the application folder. I look forward to your feedback. :-)

**Comment by sfeldkamp** [comment]
The design is great.  It solves the problem nicely.

One minor issue; saved comments disappear when the app is restarted.

I'm not in the habit of closing the app, but I wouldn't like to retype them all if I ever did so mistakenly (or if it crashed).  The timers do persist, so hopefully this won't be too much of a headache.

Thank you so much for you work on this!  I really appreciate it.  I think these changes are enough to get me to put away my notebook.

**Comment by carstengehling** [comment]
Ooops I forgot that one - nice spotted. I'll add this.

And you're very welcome :-)

**Comment by carstengehling** [comment]
https://github.com/carstengehling/jirastopwatch/releases/tag/1.4.0-pre3

This pre-release includes saving comments on exit (if you have enabled the saving of timer state)
It also includes support for typing time with decimals, like 1.25h. Be aware though, that as soon as you start the timer and it updates the display, it will have converted your input and display it in the "1h 15m" format. I could make a setting for the user to select preferred output format - that will be on the other side of christmas :-)

Let me know if this works for you.

**Comment by sfeldkamp** [comment]
1.4.0-pre3 version of the application does not run for me.  I've tried several things, but even with a 

* uninstall JiraStopWatch
* restart of the host PC (Windows 10)
* install JiraStopWatch 1.3.1, verify it runs
* download and install 1.4.0-pre2, verify it runs
* download and install 1.4.0-pre3, it does not run

I noticed that the app remembers the issues selected, even between installs.  So there must be some data cached somewhere.  I did not clear that, as I'm not sure of the location, but it could be a possible source of the conflict.

Also, here are the Windows Event Log application errors that occur:
Log Name:      Application
Source:        Application Error
Date:          12/22/2015 7:53:56 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN-7PUS3IFTJ7U
Description:
Faulting application name: StopWatch.exe, version: 1.4.0.0, time stamp: 0x567926bd
Faulting module name: KERNELBASE.dll, version: 10.0.10565.0, time stamp: 0x5614b4a7
Exception code: 0xe0434352
Fault offset: 0x000a63d8
Faulting process id: 0x1b68
Faulting application start time: 0x01d13cc0334be6a2
Faulting application path: C:\Program Files (x86)\JiraStopWatch\StopWatch.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: b0e0ebb9-a71a-48e1-a387-492948315f2f
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-22T13:53:56.352920200Z" />
    <EventRecordID>438908</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WIN-7PUS3IFTJ7U</Computer>
    <Security />
  </System>
  <EventData>
    <Data>StopWatch.exe</Data>
    <Data>1.4.0.0</Data>
    <Data>567926bd</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10565.0</Data>
    <Data>5614b4a7</Data>
    <Data>e0434352</Data>
    <Data>000a63d8</Data>
    <Data>1b68</Data>
    <Data>01d13cc0334be6a2</Data>
    <Data>C:\Program Files (x86)\JiraStopWatch\StopWatch.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>b0e0ebb9-a71a-48e1-a387-492948315f2f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          12/22/2015 7:53:56 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN-7PUS3IFTJ7U
Description:
Application: StopWatch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
Stack:
   at System.Convert.FromBase64_Decode(Char*, Int32, Byte*, Int32)
   at System.Convert.FromBase64CharPtr(Char*, Int32)
   at System.Convert.FromBase64String(System.String)
   at StopWatch.Settings.ReadIssues(System.String)
   at StopWatch.Settings.Load()
   at StopWatch.MainForm.LoadSettings()
   at StopWatch.MainForm..ctor()
   at StopWatch.Program.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-22T13:53:56.306046200Z" />
    <EventRecordID>438907</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WIN-7PUS3IFTJ7U</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: StopWatch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
Stack:
   at System.Convert.FromBase64_Decode(Char*, Int32, Byte*, Int32)
   at System.Convert.FromBase64CharPtr(Char*, Int32)
   at System.Convert.FromBase64String(System.String)
   at StopWatch.Settings.ReadIssues(System.String)
   at StopWatch.Settings.Load()
   at StopWatch.MainForm.LoadSettings()
   at StopWatch.MainForm..ctor()
   at StopWatch.Program.Main()
</Data>
  </EventData>
</Event>

**Comment by carstengehling** [comment]
Yeah my bad - The settings field for storing issue-keys and timers on exit has completely changed format to acommodate for the comments. I forgot to give the field a new name, which then meant that when reading your existing user-settings file, the Stopwatch could not parse the content of this field.

It's fixed now in https://github.com/carstengehling/jirastopwatch/releases/tag/1.4.0-pre4
