### ISSUE TITLE
Combobox cuts ID after certain characters

### ISSUE THREAD

**Issue by pjaeger16** [carstengehling/jirastopwatch#30]
The ID is cutted in the drop-down, so please check the length of the id. Cutting the description would be no Problem. 
![unbenannt](https://cloud.githubusercontent.com/assets/22491528/18903426/5a98c99a-8559-11e6-9ef2-12338a2398dc.PNG)
Thank you very much!

**Comment by carstengehling** [comment]
I've finished this, and it will be part of the next release. I'll add a zip-file here with a test-build. Feel free to test.

**Comment by pjaeger16** [comment]
Thank you very much! Zip file in the issue on github you mean?

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. Oktober 2016 10:29
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Combobox cuts ID after certain characters (#30)


I've finished this, and it will be part of the next release. I'll add a zip-file here with a test-build. Feel free to test.

**Comment by carstengehling** [comment]
[JiraStopWatchTestCBDraw.zip](https://github.com/carstengehling/jirastopwatch/files/510457/JiraStopWatchTestCBDraw.zip)

**Comment by carstengehling** [comment]
Yes - I just added it now

**Comment by pjaeger16** [comment]
Thank you, im downloading already ☺

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. Oktober 2016 10:31
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Combobox cuts ID after certain characters (#30)


Yes - I just added it now

**Comment by pjaeger16** [comment]
It works ☺ thank you!
[cid:image001.png@01D21EF4.20816490]

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. Oktober 2016 10:31
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Combobox cuts ID after certain characters (#30)


JiraStopWatchTestCBDraw.zip<https://github.com/carstengehling/jirastopwatch/files/510457/JiraStopWatchTestCBDraw.zip>
