### ISSUE TITLE
Feature Request: Work category

### ISSUE THREAD

**Issue by pjaeger16** [carstengehling/jirastopwatch#31]
We have to maintain mandatory “work category”. Perhaps you can add it as listbox like in issue selection (with option to hide it via settings). It would be nice if it will has a default value (eg. 1st one, in our environment: “Development”), so if I choose an issue, I don’t have to select it everytime.
![unbenannt](https://cloud.githubusercontent.com/assets/22491528/18903517/f16a726a-8559-11e6-93d9-2c5f56bdd125.PNG)
Its mandatory in web view, so if I open a workload of JiraStopwatch, it has selected “Please select”, but you cannot safe it again because its mandatory ;)

**Comment by carstengehling** [comment]
I've been looking at Jira's REST API. Unfortunately it is not possible to add Work Category, when posting a WorkLog:

https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-addWorklog

Maybe it is part of the rather cryptic "Entity properties", but I will need to investigate this some more.

**Comment by pjaeger16** [comment]
Thank you for looking at it. I will ask our Jira Template Team if it’s an own customer field.

Thanks!!

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Dienstag, 4. Oktober 2016 18:30
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Feature Request: Work category (#31)


I've been looking at Jira's REST API. Unfortunately it is not possible to add Work Category, when posting a WorkLog:

https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-addWorklog

Maybe it is part of the rather cryptic "Entity properties", but I will need to investigate this some more.

**Comment by carstengehling** [comment]
Have you had a chance to talk to your Jira Template Team?

**Comment by pjaeger16** [comment]
He is lookin it up, hope to get an info today

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. Oktober 2016 10:33
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Feature Request: Work category (#31)


Have you had a chance to talk to your Jira Template Team?

**Comment by pjaeger16** [comment]
Hi Carsten,

you can stop it for the moment. After examination, we detected that it is something from an own jira plugin and not a generic custom field.

Thank you for your effort!

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. Oktober 2016 10:33
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Feature Request: Work category (#31)


Have you had a chance to talk to your Jira Template Team?

**Comment by carstengehling** [comment]
Okay I'll close this issue then.
