### ISSUE TITLE
Status update feature

### ISSUE THREAD

**Issue by eviweb** [carstengehling/jirastopwatch#34]
Hi Carsten,

would it be possible to have a way to update the status of a task ?
eg. Something like a drop down menu whose options would be the different status values related to the project workflow the task belongs to.
Changing to a particular status would update the related task status in JIRA.
And when the task is done, clear the corresponding dropdown menu in JIRA StopWatch.

Thanks

Eric

**Comment by carstengehling** [comment]
In what context do you think this would apply best? When submitting the worklog (ie. in the worklog dialog)?

**Comment by eviweb** [comment]
My first thought was on the main screen next to the timer.
It would be useful to be able to select the status right after you start/stop the timer. (ie change the status to _In progress..._)

In the worklog dialog, why not an option to mark the task as _Done_ on submission.
But in that case, how to deal with a complete custom workflow ?

**Comment by carstengehling** [comment]
IMHO it's a bit outside the original scope of this tool. Also the available status changes of a task is bound to the actual workflow, that has been defined fot the project AFAIK. Also some transitions may require certain fields to be filled out - that depends on the actual Jira setup. So it's a bit more complicated to make it work in all cases.

You are very welcome to give it a shot yourself, and if you can make it work without too much hassle, I'll happily accept a pull request.

As I can see you'll have to start by digging into the API's "Get transitions" and "Do transition"

https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-getTransitions

https://docs.atlassian.com/jira/REST/cloud/#api/2/issue-doTransition

**Comment by carstengehling** [comment]
I've actually gone and done the part about doing a transition when pressing play. In the settings you can write the name of the state transitions, that you want StopWatch to apply when pressing play:

![image](https://cloud.githubusercontent.com/assets/54675/22081845/8cd86c5c-ddc5-11e6-91ca-6c613ba21484.png)

Try to build the latest source and test it. I am going to do the final release of version 1.9.0 next week, where this feature will be included.

**Comment by eviweb** [comment]
Hi Carsten,
thanks for taking into account this proposal.
It works great.
Should it be possible to add a checkbox (unchecked by default) on the worklog submission panel in a way to close a task ?
Maybe the user has to fill the possible state names for closing a task in the settings as you've done for "In Progress".
Are states defined in the setting panel case sensitive ?
Eric

**Comment by carstengehling** [comment]
The process of closing a Jira issue is much more complicated than starting it. Based on the project templates, closing an issue may require additional fields to be filled out. And this is configurable on each Jira installation - indeed for each project. So I see no easy solution to this.

**Comment by carstengehling** [comment]
Oh and I don't think that the state names are case sensitive - I send them as written to the Jira API - you will just have to check for yourself. :-)
