### ISSUE TITLE
Feature Request: Control over remaining estimate when adding worklog to Jira

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#35]
Just installed this and thanks!  Exactly what I've been looking for.  however, one feature I am missing: when I log work in Jira I get the option of what to do with the remaining estimate.  Options are:
* Automatically adjust (decrease by logged time but never below 0)
* Leave alone
* Set to a specific value
* Reduce by a specific amount

I've never really used the final one, but the first three I use.  Especially if the issue is taking longer than expected, we want to adjust the remaining amount so we have a realistic idea of how much work is left - otherwise we end up with a bunch of issues with zero remaining even though they are not done!

Would it be possible to add this functionality to the stopwatch? So, when I submit a worklog I get these options (or at least the first three!)

**Comment by carstengehling** [comment]
It's a good idea. I usually don't need this myself, but I can easily see the use for it. You are very welcome to submit a pull request, if you want this quickly done.

**Comment by slarti-b** [comment]
Thanks for the quick response. You might just get a PR soon...

Adam

**Comment by slarti-b** [comment]
I have one small usability improvement I'd like to make here: I did the new fields like the existing ones, but actually while it makes sense that return doesn't submit in the comment, if I'm in the field to set a remaining estimate manually 8or amount to reduce by) then I think enter should trigger submit.  Should i open a new issue or just send a PR or what?

**Comment by carstengehling** [comment]
I'll just do that one myself. ;-)
