### ISSUE TITLE
Feature Request: Add/remove rows dynamically

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#38]
I am in a position where I often get asked for help from other members of my team and/or input from other parts of the organisation. I would obviously like to log time on these issues, but it means the number of issues I want to have in the stopwatch app is a bit variable.  I don't like having a bunch of empty rows just in case but would prefer to be able to just click a button and add a row (or remove one) without going in to the settings screen.  

What do you think?  I'd be quite happy to implement this and send a PR (in fact, I had a play around to see how easy it would be already).

Add row is fairly straightforward. Delete/remove has a couple of options in temrs of implementation:
- It just deletes the row.  if you have un-logged time on it then hard luck (this is consistent with the behaviour of the clear/reset button today)
- The delete button is disabled if you have un-logged time (you have to either log the time or clear/reset before deleting)
- It prompts/warns you if you have un-logged time

I'm inclined towards the first simply for consistency.

Obviously, the delete row button would be disabled when only one row remains

**Comment by carstengehling** [comment]
That's actually a very good idea. :-) I've got a few things to add:

1) IMHO this should replace the option in the settings dialog. What do you think?
2) I strive to make the UI as uncluttered as possible. With that in mind, where would you place the "Add row" button?
3) Today, when having more rows than can be on the screen, a vertical scrollbar appears. When you click the "Add row" button, focus should shift to the combobox for the new row + the row should be scrolled to if needed.

And I agree with the delete implementation. Just wipe it.

**Comment by slarti-b** [comment]
1 - Maybe.  I was initially looking at a "minimal changes" implementation but the only thing added is the remove button per row plus the add button so that's an option

2 - Agree.  I have played around a bit with this already.  My thought was to put the "add row" button in the bottom next to the settings button, so it doesn't add to the overal screen real estate used by the app.  Not sure if this is the best icon but something like this:
![addrow](https://cloud.githubusercontent.com/assets/12972794/19229183/51d2e230-8ed4-11e6-8866-e5d11b51e9ee.png)

3 - Good idea
