### ISSUE TITLE
Order of filter get ignored in issue drop down

### ISSUE THREAD

**Issue by pjaeger16** [carstengehling/jirastopwatch#44]
Issues get displayd ordered by id although you have configured order by rank in filter

**Comment by carstengehling** [comment]
I think it's because I use some default sorting in the combobox. I'll have a look at this.

**Comment by carstengehling** [comment]
I just tested this with my tria. Jira Cloud account. Sorting order _is_ respected, when you save the sorting in your filter. However: When you have selected a filter in Jira StopWatch, what is actually saved is the JQL query from the filter. So if you change the sorting inside your Jira filter and save it, you will have to click the StopWatch filter drop-down again and select the filter once more. Then the new JQL (containing the new sorting) will be fetched and used.
