### ISSUE TITLE
Improvement: Keyboard Handling

### ISSUE THREAD

**Issue by pjaeger16** [carstengehling/jirastopwatch#45]
To jump faster through issue controls, it would be nice if arrow keys up and down could move focus to the same kind of control. So if you have selected Dropdown of issue control #2, up arrow would move focus to issue control #1 and down to issue control #3. Same for Start/stop timer, submit worklog etc.

Alt+Enter should move to start/stop timer, another alt+enter on start/stop timer should move to submit button (or directly execute submit in one step).

**Comment by carstengehling** [comment]
I've been thinking about keyboard handling for some time now - just haven't gotten to do it yet. I'll give your suggestions some thought.

I've thought about doing some "currently selected row" that can be moved with ALT-Arrow UP/DOWN (or CTRL-arrow, if ALT-arrow conflicts with the comboboxes). And then on the "currently selected row" you have shortcut for start/stop, submit, and maybe also reset and delete.

**Comment by pjaeger16** [comment]
Thank you and a happy new year ☺


Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Montag, 9. Januar 2017 10:10
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Improvement: Keyboard Handling (#45)


I've been thinking about keyboard handling for some time now - just haven't gotten to do it yet. I'll give your suggestions some thought.

I've thought about doing some "currently selected row" that can be moved with ALT-Arrow UP/DOWN (or CTRL-arrow, if ALT-arrow conflicts with the comboboxes). And then on the "currently selected row" you have shortcut for start/stop, submit, and maybe also reset and delete.

**Comment by pjaeger16** [comment]
Oh my gosh, Sorry for that! you are right, had saved stopwatch filter without order..

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 22:26
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Order of filter get ignored in issue drop down (#44)


I just tested this with my tria. Jira Cloud account. Sorting order is respected, when you save the sorting in your filter. However: When you have selected a filter in Jira StopWatch, what is actually saved is the JQL query from the filter. So if you change the sorting inside your Jira filter and save it, you will have to click the StopWatch filter drop-down again and select the filter once more. Then the new JQL (containing the new sorting) will be fetched and used.

**Comment by carstengehling** [comment]
Philip could you try to install this pre-release and see if it works as you intended?

[jirastopwatch-setup-1.9.1-pre1.zip](https://github.com/carstengehling/jirastopwatch/files/754001/jirastopwatch-setup-1.9.1-pre1.zip)

The shortcuts are described her:

[stopwatch keyboard shortcuts.pdf](https://github.com/carstengehling/jirastopwatch/files/754004/stopwatch.keyboard.shortcuts.pdf)

Cheers

**Comment by carstengehling** [comment]
This version has a slightly better functionality when moving current row up and down. Control focus was not move - it is now.

[jirastopwatch-setup-1.9.2-pre1.zip](https://github.com/carstengehling/jirastopwatch/files/754044/jirastopwatch-setup-1.9.2-pre1.zip)

**Comment by pjaeger16** [comment]
Looks good ☺ i will give you feedack in a while how good it works.


Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Montag, 6. Februar 2017 09:46
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Improvement: Keyboard Handling (#45)


This version has a slightly better functionality when moving current row up and down. Control focus was not move - it is now.

jirastopwatch-setup-1.9.2-pre1.zip<https://github.com/carstengehling/jirastopwatch/files/754044/jirastopwatch-setup-1.9.2-pre1.zip>

**Comment by carstengehling** [comment]
Great! I'm using it myself now too - to get a feel for, if anything could be improved.

**Comment by slarti-b** [comment]
Saw this and decided to try it too.  Looks good.  However, I might suggest a couple more keyboard shortcuts:

- Ctrl-o - open the issue in your browser 
- Ctrl-v - copy issue ID to clipboard (even if not in that field, but not if in the submit worklog form, only from issue control)

**Comment by carstengehling** [comment]
Yes I thought about the CTRL-O myself yesterday too. :-) 👍 

Copy Issue-ID: Good idea - although I'll use the conventional CTRL-C instead (which you proably also meant)

**Comment by slarti-b** [comment]
Yes, I meant Ctrl-c ! :)

**Comment by pjaeger16** [comment]
If I select jira stopwatch, go to another window and press alt+tab, its not possible to come back to jira stopwatch, so “only keyboard” usage not possible atm.

Is there a  possiblity to get highlight back via shortcut (put stopwatch in systray and with free given shortcut in settings (eg. Strg+alt+j) , jira stopwatch is selected in foreground) ?

thx


Von: Adam Conway [mailto:notifications@github.com]
Gesendet: Donnerstag, 9. Februar 2017 13:55
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Improvement: Keyboard Handling (#45)


Yes, I meant Ctrl-c ! :)

**Comment by carstengehling** [comment]
> If I select jira stopwatch, go to another window and press alt+tab, its not possible to come back to jira stopwatch, so “only keyboard” usage not possible atm.

Hmm... I do this all the time. ALT-TAB should switch between any application, including StopWatch, and indeed it works fine for me.

**Comment by carstengehling** [comment]
@slarti-b I've implemented the remaining keyboard shortcuts as well:

CTRL-O open Issue in the browser
CTRL-C / CTRL-V copy/paste issuekey of current issue (no matter if focus is in the combobox or not)

Try to fetch the latest source and try it.

**Comment by slarti-b** [comment]
Looks good.  One small thing: you mention the keyboard shortcut for each button in it’s tooltip (nice) except for the “add a row” button.  Ctrl+N works for that but isn’t mentioned in the tooltip.

Adam

**Comment by carstengehling** [comment]
Fixed :-)

**Comment by slarti-b** [comment]
No, it's not :(

I've got the latest master I think, and can see the shortcut being mentioned in the tooltip in the code but it's not showing.
![image](https://cloud.githubusercontent.com/assets/12972794/23132998/225ee92c-f798-11e6-8838-a20a403ce8ee.png)

The tooltip is also set in Mainform::InitializeIssueControls as follows
```
// Reset status 
this.ttMain.SetToolTip(this.pbAddIssue, "Add another issue row");
```

So I guess that's coming in after and removing it.  Maybe should be a constant/function to always be the same in both places?

**Comment by carstengehling** [comment]
So sorry - forgot to push the commit... *blush*

https://github.com/carstengehling/jirastopwatch/commit/f92d051fbd13defff7bbc4eca57f8db5bbd26496

But yeah - stuff like this ought to be defined in constants.

**Comment by slarti-b** [comment]
No problem.  Looks good now.
