### ISSUE TITLE
Improvement: Add a reset button

### ISSUE THREAD

**Issue by pjaeger16** [carstengehling/jirastopwatch#46]
After sprint is over, we have to clear all dropdown fields manually.
Please add a reset button, which clears all selected issues and set times back to 0m.
Thank you very much.

**Comment by carstengehling** [comment]
Hey Phillip,

Have a look at the pre-release here: https://github.com/carstengehling/jirastopwatch/releases/tag/1.9.0-pre1

It has a new (IMHO better) way of handling adding/removing Issue-slots. This will make the above work much easier.

**Comment by carstengehling** [comment]
Phillip have you tried the new 1.9.0 that I released - with the "add" and "remove" buttons? Do you still think a "global" reset button is needed?

**Comment by pjaeger16** [comment]
Hi Carsten,

its only a nice to have. I could also now delete all rows and add new ones very quick, but reset button would be faster ☺

thank you

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Sonntag, 5. Februar 2017 22:34
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Improvement: Add a reset button (#46)


Phillip have you tried the new 1.9.0 that I released - with the "add" and "remove" buttons? Do you still think a "global" reset button is needed?

**Comment by carstengehling** [comment]
I know, but I think the use case for a global reset button is very narrow. And as I've stated earlier, I don't want to clutter the application with features.
