### ISSUE TITLE
Improvement: Total worklog of today

### ISSUE THREAD

**Issue by pjaeger16** [carstengehling/jirastopwatch#47]
In addition to the total of non-submitted worklogs of time tracker, there should be a display of users total worklogs time which are booked for today. It should be updated after submission of tracked time.
If you cannot get it via api, it would be an alternative to only show the todays tracked time via jira stopwatch  so you can (export times to a local file and) make an addition every time.

Thank you very much.

**Comment by carstengehling** [comment]
Hi Philip,

I cannot find anything in the Jira REST API, that enables me to fetch all the worklogs, that a single user has posted on a specific date. Only way is to poll through the issues, and that doesn't really work that well, if you remove an issue key from StopWatch during the day (which I do a lot, once I'm done with it).

You are welcome to fiddle with this yourself and if you come up with a solution, that you are happy about, I'll gladly accept a PR.

**Comment by pjaeger16** [comment]
Could you make a local log instead?

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Montag, 20. März 2017 12:56
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Improvement: Total worklog of today (#47)


Hi Philip,

I cannot find anything in the Jira REST API, that enables me to fetch all the worklogs, that a single user has posted on a specific date. Only way is to poll through the issues, and that doesn't really work that well, if you remove an issue key from StopWatch during the day (which I do a lot, once I'm done with it).

You are welcome to fiddle with this yourself and if you come up with a solution, that you are happy about, I'll gladly accept a PR.

**Comment by carstengehling** [comment]
Possibly yes. Then it would need to be reset automatically on change of current date. So you should store the current date in the user config.

**Comment by pjaeger16** [comment]
Could you develop this?

Beste Grüße
Best regards

Philipp Jäger
SAP Basis Administrator

Von: Carsten Gehling [mailto:notifications@github.com]
Gesendet: Montag, 20. März 2017 13:08
An: carstengehling/jirastopwatch <jirastopwatch@noreply.github.com>
Cc: Jäger, Philipp <philipp.jaeger@cgm.com>; Author <author@noreply.github.com>
Betreff: Re: [carstengehling/jirastopwatch] Improvement: Total worklog of today (#47)


Possibly yes. Then it would need to be reset automatically on change of current date. So you should store the current date in the user config.

**Comment by slarti-b** [comment]
@pjaeger16: Not sure if you know about it already but we use a Jira plugin (https://marketplace.atlassian.com/plugins/org.everit.jira.timetracker.plugin/server/overview) which provides a nice page within Jira which lists the time logged by the current use per day, including total time.  it's not bad (although I would like more flexibility to customize the columns in the view)

Personally, I think it's more appropriate there - the stopwatch is to help log time, not to audit or manage existing time logs in my view

**Comment by asztal** [comment]
I also use Everit's time tracker and it's pretty useful. It would be nice
to see my previous work log entries in JIRA stopwatch somehow, for those
times when I want to "fill in the blanks", but the Everit plugin actually
works OK for that too.

Adam Conway <notifications@github.com> ezt írta (időpont: 2017. márc. 20.,
Hét 15:54):

**Comment by carstengehling** [comment]
> Could you develop this?

I don't personally find the feature particularly useful, especially since it it would require quite a lot to make it accurate. But if you could implement it yourself or know someone else who could, feel free to make a pull request.
