### ISSUE TITLE
Bug in 1.9 beta: Exception first time I try to log time

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#49]
Running with 1.9 beta (6bbe5c4aa5ed478ac7e968d7ae411d54b9c05705) i have had a few occassions where I thought I had submitted but it was still there, this time Visual Studio came up with an exception. null reference in IssueControl.cs::UpdateRemainingEstimate at
`() => RemainingEstimate = timetracking.RemainingEstimate`
Continuing the app was there with the time still saved, clicking submit again worked fine.

This is connected to control of remaining stuff I did, so I'll try and have look this evening if I get time (or at the weekend otherwise) unless you find the answer first :)

**Comment by carstengehling** [comment]
Would you be able to send me the stacktrace?

**Comment by carstengehling** [comment]
I think I can guess why:

``  timetracking = jiraClient.GetIssueTimetracking(key);

GetIssueTimetracking() can return null if - for some reason - your call to the Jira API fails. so you should do a check for that before continuing. I'll add this.

**Comment by slarti-b** [comment]
OK!  I have been away from the computer all weekend.  Just put it on to look actually, was halfway through a comment on another issue.

Will try and repeat and confirm

**Comment by carstengehling** [comment]
FYI: I finally released version 1.9.0 :-)

**Comment by slarti-b** [comment]
Nice!  Except that it crashes for me! Have created a new issue at https://github.com/carstengehling/jirastopwatch/issues/50 since it’s not connected to this (and this is closed)

Adam
