### ISSUE TITLE
InvalidOperationException on control 'tbTime'

### ISSUE THREAD

**Issue by avlcodemonkey** [carstengehling/jirastopwatch#5]
I've just downloaded the project and started experimenting with it.  It looks very promising.  I'm noticing an error when I initially run the project though.

At IssueControl.cs:100, I'm getting the error:

`An exception of type 'System.InvalidOperationException' occurred in System.Windows.Forms.dll but was not handled in user code

Additional information: Cross-thread operation not valid: Control 'tbTime' accessed from a thread other than the thread it was created on.`

If I continue from the error, it seems to run fine though.  Any suggestions?

**Comment by carstengehling** [comment]
Hmm... I'll look into that and release a bug fix. Nice spotted, thanks.

**Comment by carstengehling** [comment]
Could you supply some more info:

- Were you running the app from Visual Studio or did you install the program and run it from there?

- Can you remember what you did just prior to the error occurring? As full description as possible will help be a great deal.

TIA

**Comment by avlcodemonkey** [comment]
Carsten, the issue only occurs when running in Debug in Visual Studio. After some digging I found this on [SO](http://stackoverflow.com/questions/3972727/why-is-cross-thread-operation-exception-not-thrown-while-running-exe-in-bin-debu).

I added 

`Control.CheckForIllegalCrossThreadCalls = false;`

at IssueControl.cs:184 and it fixed the issue for me.  Thanks for your time.

**Comment by carstengehling** [comment]
What I cannot really read out of this is, if the exception is indicating a possible bug. I try to assure, that all cross-thread acces to UI components are wrapped in a <control>.Invoke() method.

Could I get you to try again and post the entire stacktrace here? I would very much like to make sure, that it isn't because of a bug.

BTW: What version of Visual Studio are you running?

**Comment by avlcodemonkey** [comment]
I'm running Visual Studio 2015 Pro on Win10.  I tried uncommenting the fix I posted before so I could get the full stack trace, and now I can't recreate the bug. I tried pulling a fresh copy of the repo, and can't recreate with it either. It must have been a quirk of my environment.  I'll add the stack trace if I can figure out how to recreate it.  Until then, this looks like a non-issue.

**Comment by carstengehling** [comment]
Great news - since i wasn't able to reproduce it myself ;-) Thanks for the effort!
