### ISSUE TITLE
1.9 Won't start: DPAPI was unable to decrypt data

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#50]
I download the 1.9 and installed (didn’t unistall any old one – but I’ve been running dev version from visual studio for a while anyway).  Install went fine.  Tried running, either via start menu or directly from C:\Program Files (x86)\Carsten Gehling\Jira StopWatch.  In both cases I just get the following error:
![image](https://cloud.githubusercontent.com/assets/12972794/22266170/9045703a-e287-11e6-8aef-8a79a8afa02e.png)

The log file report the following:
```
2017-01-24 22:40:10: Unhandled UI Exception
2017-01-24 22:40:10: DPAPI was unable to decrypt data.
2017-01-24 22:40:10:    at StopWatch.DPAPI.Decrypt(Byte[] cipherTextBytes, Byte[] entropyBytes, String& description)
   at StopWatch.DPAPI.Decrypt(String cipherText, String entropy, String& description)
   at StopWatch.Settings.Load()
   at StopWatch.MainForm..ctor()
   at StopWatch.Program.Main()
```

Could this be because I’ve been running a dev version? Getting an old key from somewhere? The StopWatch.exe.config in C:\Program Files (x86)\Carsten Gehling\Jira StopWatch 
looks like the default blank one from a new install.

Log and config files (as zip since it won't allow the other extensions)
[StopWatch#50.zip](https://github.com/carstengehling/jirastopwatch/files/727928/StopWatch.50.zip)

**Comment by carstengehling** [comment]
Try to delete your config files in C:\users\<username>\AppData\Local\StopWatch

**Comment by slarti-b** [comment]
I removed all the subfolders to that folder. Gets me further.  The program now starts.  I enter the URL to my Jira but it doesn't connect.  Clicking the _Not Connected_ simple opens a window saying _Jira StopWatch could not connect to your Jira server. Error returned:_ - but without an error.  note that it never gets as far as asking for my username or anything.

![image](https://cloud.githubusercontent.com/assets/12972794/22266994/c196cf0a-e28a-11e6-932f-8672d91cf57d.png)

I have enabled logging of Jira requests, but no log file is generated!

Must have screwed up my env somehow - getting the same behaviour from Visual Studio now!  Even if i revert to the last-but-one commit (which is what i was running earlier today) and clean the C:\Users\adam.conway\AppData\Local\StopWatch folder it still does the same.  Will try and debug a bit

**Comment by slarti-b** [comment]
OK, it works now.  My fault for having been too long since I set it up - although I think it's a UI bug.  Clicking _Not Connected_ shows the above, with an empty error message.  Clicking the padlock next to _Not Connected_ allows you to enter your username/password and connect.

I think that:

- When you first enter/change the jira base URL, you should be prompted for the login credentials when you save and close the settings form.  Same if you start the app with a non-default Jira URL but no login credentials
- If you click _Not Connected_ and you don't have any credentials entered it should either report that or prompt for credentials.

But it's working for me now.  Thanks

**Comment by slarti-b** [comment]
Minor note too: While the download link correctly links to latest (1.9) the text on http://carstengehling.github.io/jirastopwatch/ still says _1.8.0_

**Comment by carstengehling** [comment]
**Regarding the download link:** I have actually bought a real domain and established a new homepage for StopWatch: http://jirastopwatch.com - I just haven't gotten around to change all urls on Github, Atlassian Marketplace etc. yet. It would be nice if Github pages (as the old url uses) could do a permanent redirect to the new url. But I guess I'll have to make a "refresh page" for that myself.

**Regarding connection:** At this point, I really don't know, why I made entering username/password on a separate dialog, and not just a part of the settings dialog. I think I'll change that, so that the padlock can be gone forever.

**Comment by slarti-b** [comment]
OK!  Makes sense as a separate dialogue to me only if you don’t check “remember my password” to me – but then it should run automatically when you start the app. But I really can’t see anyone using like that for any significant use…



Adam

**Comment by carstengehling** [comment]
Exactly! I don't try to make StopWatch fit every case - instead I hope to make it match the most common use cases. That is always oppionated and based heavily on assesments of course. But I think, moving login info into the settings dialog, will fit most users of StopWatch.

**Comment by carstengehling** [comment]
BTW: Thank you for being so active in the development and general shaping of this application. You've got good arguments and serious oppinions. I really appreciate it!

**Comment by slarti-b** [comment]
No problem. Thank you for the application – it was just what I was looking for.

Adam
