### ISSUE TITLE
1.9.0 release fails to install over 1.9.0-pre1 

### ISSUE THREAD

**Issue by eviweb** [carstengehling/jirastopwatch#51]
Hi Carsten,
the newer release `1.9.0` fails to install over its pre-release `1.9.0-pre1` with the following error message `Unable to install because a newer version of this product is already installed.`
Eric

**Comment by carstengehling** [comment]
Yes - if you run with the pre-release, you will need to uninstall it first. No way around that with the current setup-systems.

**Comment by eviweb** [comment]
ok, thanks
Eric
