### ISSUE TITLE
JiraStopWatch cannot connect to a jira server.

### ISSUE THREAD

**Issue by pklinkov** [carstengehling/jirastopwatch#56]
JiraStopWatch v.1.9.0. cannot connect to a Jira-Server (JIRA V7.2.1). Version 1.8.0 has no problems to connect.
Following two lines are output in the jirastopwatch.log:

> 16.02.2017 07:54:01 Request: https://jira.******.net/rest/api/2/filter/favourite
> 16.02.2017 07:54:01 Response: OK - []

Version 1.8.0:
<img src="https://cloud.githubusercontent.com/assets/4760271/23010967/88712bc6-f41e-11e6-834c-626ab1562118.PNG" width="150">
Version 1.9.0:
<img src="https://cloud.githubusercontent.com/assets/4760271/23010966/88515396-f41e-11e6-8e5b-13a8055dcdb6.PNG" width="150">

**Comment by carstengehling** [comment]
Could you verify the following:

# Click on the gear-icon and check that your base-url is correct
# Click on the padlock-icon and check that your username/password is correct

I will need the entire logfile, in order to figure out, what is wrong.

**Comment by pklinkov** [comment]
My Bad. I was clicking on the red "Not connected" link. It turns out this is different from the padlock button.
