### ISSUE TITLE
Bug in pre-1.9.1: Keyboard control doesn't update issue info

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#57]
To repeat:
- tab to stopwatch
- Ctrl-N to get new row
- Ctrl-V to paste in URL to issue
- Ctrl-P to start timer

The issue ID is there and the time started, but the info (issue title) is not updated until you tab out of the issue control box.

Expected: wither the Ctrl-V directly or certainly the Ctrl-P would trigger any "finsihed editing"/blur events and update the issue title

**Comment by carstengehling** [comment]
Could you test, if this fix works as you would expect?

**Comment by slarti-b** [comment]
Looks good

**Comment by slarti-b** [comment]
Sorry, re-opening this.  The fix you did works if the issue key was initially blank 8for a new row) but not if you change issue key.
To repeat:

1. Put an issue key in a row
2. Start the timer.  Check the issue name is correct
3. Stop the timer
4. Change the issue key to a different one
5. Use Ctrl-P to start the timer

What happens: the timer starts but it still has the old issue title listed.  When you tab out of the field the issue name is updated.

Expected: as soon as you start the timer (or log or anything) the issue summary should be updated, even if focus remains in the issue key field.

**Comment by slarti-b** [comment]
Note: my last comment only applies if you manually change the issue id.  If you paste in a new one it does update the title properly

**Comment by carstengehling** [comment]
Try it out now

**Comment by slarti-b** [comment]
Looks good.
