### ISSUE TITLE
Bug in pre-1.9.1: Can't open issue list with mouse

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#59]
The new keyboard short-cut for opening the issues list (form the filter) works fine.  But clicking the drop-down arrow to open the issues list with the mouse results in it opening and immediately closing again!

**Comment by carstengehling** [comment]
This happened because I set the entire row as "current" (changed background color of the row) on mousedown/up event. This apparently causes the dropdown box to loose focus and close. Row is now only set to current AFTER selecting an item in the dropdown list.

**Comment by slarti-b** [comment]
It works in terms of opening the drop-down but... now if you click in the text field for the issue ID (but don't open the drop-down) it doesn't select the row.  So, if I click on an existing issue ID and then do Ctrl-P then it starts the timer on the wrong row!

**Comment by carstengehling** [comment]
It's a tricky thing with comboboxes, because they are actually a combination of 2 controls. But I'll try to fiddle with it.

**Comment by slarti-b** [comment]
I understand that - I had the same issue trying to do the paste thing the first time.  If it comes down to it, I think the version before the fix for this issue was less of a problem.  it was a bug, but an easily spotted one for the end user.  This version is updating other rows than expected and much easier to miss what it did :)

**Comment by carstengehling** [comment]
I think, that I can do the same trick with hooking into the textbox' WM_ENTER message, and thereby be able to distinguish between events.

**Comment by carstengehling** [comment]
It seems to work by hooking into WM_LBUTTONDOWN. Give it a spin and let me know what you think.

This really brings me back to the good old days with Charles Pretzold's "Programming Windows"... :-)

**Comment by slarti-b** [comment]
Still not fully working for me.  Updated to df8fb47805233428d0fafa8c26b92d923da45ff0 and the focus still doesn't follow clicking on the issue key dropd-down.  For example, 

1. Start with a stopwatch with some rows.
2. Add a new row
3. Move focus up to the top row
4. Click on the arrow to open the drop-down on the empty row - the cursor moves to the field, but the selected focus is still on the top
5. If I selected an issue from the list it goes correctly in the new row, but if I just close the drop-down again I am left with the cursor in the new row, but the "selected row" is the top row still.  
- If I start writing I am writing in the issue id field on the new row (but with the selected row still being the top row)
- If I paste a URL it gets pasted into the top row

I think the row should get selected when you click the drop-down button, if possible

I did a little video to illustrate, but had to zip it to be allowed to attach it:
[Mar 15 2017 9-45 AM.zip](https://github.com/carstengehling/jirastopwatch/files/843697/Mar.15.2017.9-45.AM.zip)

**Comment by carstengehling** [comment]
> I think the row should get selected when you click the drop-down button, if possible

I agree, but it is exactly this behaviour that caused the original bug about the drop-down closing immediately. This is what happened before I started making changes:

1. User click on drop-down arrow
2. Drop-down box (window) is opened
3. My eventhandler set row as "current", which results in
4. The new current IssueControl's background color is changed

And it is the thing in 4) that causes the drop-down box to close again. It's this line in the IssueControl class, that causes the box to close:

![image](https://cloud.githubusercontent.com/assets/54675/23942721/88a61b06-096d-11e7-8911-14931286fd6a.png)

Without this, I did not need all these workarounds.

**Comment by slarti-b** [comment]
Hmm... I guess what you really want is to re-order so it goes 1 - 3 - 4 - 2 then?  But that may not be possible with the combined control?

Could you delegate an event to re-open the drop-down after the colour change?  Maybe trigger a customer event there, which you hook in to and open the drop-down if the original event was clicking on that row?

**Comment by carstengehling** [comment]
> Hmm... I guess what you really want is to re-order so it goes 1 - 3 - 4 - 2 then? But that may not be possible with the combined control?

Exactly! So I need to do some digging to figure out how this can be done.

I've just discovered another issue that happens now as a consequence of the current changes. Try to click on the drop-down arrow, and then use the arrow-down key to move through the items in the drop-down box. After pressing once, the box closes.

**Comment by carstengehling** [comment]
I think I nailed it now. I simply used the wrong event on the combobox, which caused the last bug, that I described.

Now the row will be marked as current, when you select an item on the dropdown list.

**Comment by slarti-b** [comment]
Sorry, this still leaves a gap where you end up in the row other than the one you expect.
1. I had focus on the top row but there were several rows (including an empty one but I don't think that matters)
2. Have the URL to a Jira issue in the clipboard
3. Click the drop-down arrow on a row other than the focused
4. Ctrl-V to paste the URL - pastes into top (active) row, not the row you clicked in since th row selection hasn't updated yet)
5. Ctrl-P to start timer, again, starts the current active row

**Comment by carstengehling** [comment]
Yes but that really sounds a bit academic IMHO. I can't really see anyone doing that particularly combination of actions. If you've clicked the drop-down arrow, you probably would not be pasting in an issue key.

In any case, I've not been able to make it work that you change current row on clicking the arrow button without the dropdown closing. You're very welcome to give it a shot if you want.

**Comment by slarti-b** [comment]
I'll see if I get the chance.  I suppose it's not so much that someone would do that deliberately, just that the dropdown button is an obvious target when clicking to select the row :)

**Comment by carstengehling** [comment]
It is :-) In any case I'll close the issue for now. If you figure out something, throw me a PR.
