### ISSUE TITLE
Improvement: Close to system tray

### ISSUE THREAD

**Issue by rszuster** [carstengehling/jirastopwatch#62]
Shouldn't need much explanation, it would be nice to be able to select the action of the closing "X" button.
I find myself closing the window by mistake all the time and it isn't until i try to switch tasks that i realize the tool is not running and i lost track of the time spent on the task.

**Comment by carstengehling** [comment]
You have some options already, that will help you in these cases:

![image](https://cloud.githubusercontent.com/assets/54675/23892592/8493240a-089b-11e7-93f2-8eacb6b81127.png)

This setting will make sure, that time-tracking continues even if the application is closed. I'm not a fan of closing to system tray - you have an option to make the minimize button do that though.
