### ISSUE TITLE
Improvement: Use Actual Start Time as start time instead of working backwards from submit time

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#66]
This is more a question than an issue, but sort-of a feature request.  I see from the release notes that in 1.8 _When submitting worklog, StartTime will also be set. The value will be equal to "now minus logged work-time"_.  Why is the start time not remembered from the first time you press play on that issue[1]?

I've had a few occasions where I forgot to log the time before closing.  I have it set to pause timer and remember time both on screen lock and on closing stopwatch.  I usually hibernate my computer overnight.  So, I come in the next morning, open up, see the time there and log it - and it logs to the wrong day!  So, I'd prefer it to use the actual start time (I'd rather have a wrong end-time than wrong start-time since the day is important to me but the time of day isn't so much.

Wondered if you saw a problem with this approach (at least as an option)?  If not, I make make it a feature request (or even just a PR:))

[1] Obviously, if you submit a work-log on that issue this would reset to the next time you press play

**Comment by carstengehling** [comment]
> Why is the start time not remembered from the first time you press play on that issue?

No real reason I think. I'm not the original author of this specific feature. Here's the conversation, that led to his PR: https://github.com/carstengehling/jirastopwatch/issues/26

I'm quite sure, that @asztal will be happy too, if you change this behaviour. Feel free to submit a PR on this - I'm a bit short on time myself at the moment.

I did a couple of nice-to-have stuff the other day, and I'd like to release soon, since there are now so many improvements compared to the current release. So let me know if you get time to work on this soon, then I will wait.

**Comment by asztal** [comment]
I'm perfectly happy for this functionality to be changed in whatever way
makes sense, I'm not particularly attached to the current behaviour  -
really my pull request was more of a "quick win" in terms of payoff vs.
time spent implementing it. I don't pause the timer very often so it was
generally fairly accurate for me anyway. I can certainly see why your
suggestion would make more sense if the timer is paused often.

Carsten Gehling <notifications@github.com> ezt írta (időpont: 2017. márc.
20., Hét 10:34):

**Comment by slarti-b** [comment]
I will have a look at this at some point, but not much time myself just now either so don't wait for this for the next version.

**Comment by carstengehling** [comment]
Okay then I'll release the next version in a couple of days.

**Comment by carstengehling** [comment]
@slarti-b before you start on this: At the moment, all data regarding the timers are very tightly coupled to the UI, which leads to some things being hard to change and implement. I've had an ambition, that I want to decouple this after releasing the 2.0 version. So any development you do now might be agains a very moving target.
