### ISSUE TITLE
Crash on startup on windows 10 machine

### ISSUE THREAD

**Issue by jonatanmichiels** [carstengehling/jirastopwatch#67]
Hi,

I have some trouble launching JIRA Stopwatch.
I'm running windows 10 and .NET 4.6.
It fails with the following error in the log file.
Is there someone who has a similar issue like this who can help me?
The error is in Dutch, translation of the first line:

`hexadecimale value 0x00, is an invalid character. line 9, position 1.`

Complete error:

`3-3-2017 08:49:02: Unhandled UI Exception
3-3-2017 08:49:02: ., hexadecimale waarde 0x00, is een ongeldig teken. Regel 9, positie 1. (C:\Users\jonatan.michiels\AppData\Local\StopWatch\StopWatch.exe_Url_hu5aebzrblzprq0ngyutxvdprfguhheg\1.8.0.0\user.config line 9)
3-3-2017 08:49:02:    bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   bij System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   bij System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   bij System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   bij System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   bij System.Configuration.ApplicationSettingsBase.Upgrade()
   bij StopWatch.Settings..ctor()
   bij StopWatch.MainForm..ctor()
   bij StopWatch.Program.Main()
7-3-2017 08:26:27: Unhandled UI Exception
7-3-2017 08:26:27: ., hexadecimale waarde 0x00, is een ongeldig teken. Regel 9, positie 1. (C:\Users\jonatan.michiels\AppData\Local\StopWatch\StopWatch.exe_Url_hu5aebzrblzprq0ngyutxvdprfguhheg\1.8.0.0\user.config line 9)
7-3-2017 08:26:27:    bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   bij System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   bij System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   bij System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   bij System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   bij System.Configuration.ApplicationSettingsBase.Upgrade()
   bij StopWatch.Settings..ctor()
   bij StopWatch.MainForm..ctor()
   bij StopWatch.Program.Main()
7-3-2017 08:38:36: Unhandled UI Exception
7-3-2017 08:38:36: ., hexadecimale waarde 0x00, is een ongeldig teken. Regel 9, positie 1. (C:\Users\jonatan.michiels\AppData\Local\StopWatch\StopWatch.exe_Url_hu5aebzrblzprq0ngyutxvdprfguhheg\1.8.0.0\user.config line 9)
7-3-2017 08:38:36:    bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   bij System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   bij System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   bij System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   bij System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   bij System.Configuration.ApplicationSettingsBase.Upgrade()
   bij StopWatch.Settings..ctor()
   bij StopWatch.MainForm..ctor()
   bij StopWatch.Program.Main()
20-3-2017 13:41:49: Unhandled UI Exception
20-3-2017 13:41:49: ., hexadecimale waarde 0x00, is een ongeldig teken. Regel 9, positie 1. (C:\Users\jonatan.michiels\AppData\Local\StopWatch\StopWatch.exe_Url_hu5aebzrblzprq0ngyutxvdprfguhheg\1.8.0.0\user.config line 9)
20-3-2017 13:41:49:    bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   bij System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   bij System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   bij System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   bij System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   bij System.Configuration.ApplicationSettingsBase.Upgrade()
   bij StopWatch.Settings..ctor()
   bij StopWatch.MainForm..ctor()
   bij StopWatch.Program.Main()
21-3-2017 08:26:17: Unhandled UI Exception
21-3-2017 08:26:17: ., hexadecimale waarde 0x00, is een ongeldig teken. Regel 9, positie 1. (C:\Users\jonatan.michiels\AppData\Local\StopWatch\StopWatch.exe_Url_hu5aebzrblzprq0ngyutxvdprfguhheg\1.8.0.0\user.config line 9)
21-3-2017 08:26:17:    bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   bij System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   bij System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   bij System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   bij System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   bij System.Configuration.ApplicationSettingsBase.Upgrade()
   bij StopWatch.Settings..ctor()
   bij StopWatch.MainForm..ctor()
   bij StopWatch.Program.Main()
21-3-2017 08:28:49: Unhandled UI Exception
21-3-2017 08:28:49: ., hexadecimale waarde 0x00, is een ongeldig teken. Regel 9, positie 1. (C:\Users\jonatan.michiels\AppData\Local\StopWatch\StopWatch.exe_Url_hu5aebzrblzprq0ngyutxvdprfguhheg\1.8.0.0\user.config line 9)
21-3-2017 08:28:49:    bij System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   bij System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   bij System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   bij System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   bij System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   bij System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   bij System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   bij System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   bij System.Configuration.ApplicationSettingsBase.Upgrade()
   bij StopWatch.Settings..ctor()
   bij StopWatch.MainForm..ctor()
   bij StopWatch.Program.Main()`

**Comment by carstengehling** [comment]
It's a known problem, which will be fixed in the next release. Your user-config file has somehow become corrupt. The best solution is to delete the config file. You find it in:

C:\Users\<username>\AppData\Local\StopWatch

Just delete everything in this folder and start StopWatch again. You will need to reconfigure the Jira URL, login etc.

**Comment by jonatanmichiels** [comment]
This fixed my problem, Thank you!
