### ISSUE TITLE
Tray icon missing

### ISSUE THREAD

**Issue by evladutoiu** [carstengehling/jirastopwatch#69]
Hey! I just updated to version 2.0
Looks good, works awesome, but...
I have it set to minimize to tray, but every time I minimize it, there is no icon in the tray, only way to bring it up is by opening it from the start menu or desktop shortcut...

I have restarted my computer and to no avail!

**Comment by carstengehling** [comment]
Argh! I think that Visual Studio hates me. I have previously discovered, that icon resources are sometimes "unlinked" from the main form - both the main icon and, as is obviously now the case, the system tray icon. I wasn't aware of this unfortunately. I'll make a bugfix ASAP and get this releases.

**Comment by evladutoiu** [comment]
I appreciate it very much!

Manu Vladutoiu

**Comment by carstengehling** [comment]
I just released a new version with a fix for this.
