### ISSUE TITLE
Multiple timers running at the same time

### ISSUE THREAD

**Issue by evladutoiu** [carstengehling/jirastopwatch#7]
Could you add the possibility to work on more than just one issue at a time? When you click the play button to start recording time it pauses the active one, and i'd like to be able to leave it on. Sometimes I have a task that maybe compiles in the background for 5 minutes and I can do something else in the meantime, but still want the timer on the initial task to run, or clocking a phone call while working on something else. Hope that makes sense!

**Comment by carstengehling** [comment]
No this does not make sense to me. This is the core functionality in Jira StopWatch. It is used to track what _you_ are concentrating on at a given time, not anything else. So no, I cannot see a use-case where this would be a good thing to have.

**Comment by evladutoiu** [comment]
I understand the thinking behind it, but 4 out of 10 times I would like to be able to time two things at the same time. Is it possible to make this an option that someone could enable? I understand that probably most people prefer the current setup!

**Comment by carstengehling** [comment]
It's a very fundamental change. It could be done as an option, but this means that you will _always_ be manually pausing all timers

**Comment by evladutoiu** [comment]
True, but in my particular case, I currently have to manually add the difference in minutes to the paused timer which was working in the background. 
That's the reason I was asking if you could make that an option in the settings screen because that way, it would only be enabled by those in similar situations as myself. Otherwise anyone else can continue using the app just as it is right now! 

Thank you for understanding! Your app is really nice and extremely useful! Appreciate all your time!

**Comment by carstengehling** [comment]
@evladutoiu Try to grab the zip-file from this page: https://github.com/carstengehling/jirastopwatch/releases/tag/miltitimers-beta1

Unzip the content into the folder where you have Jira Stopwatch installed. It's a tryout for this issue. In the settings window there is a new checkbox "Allow multiple timers running simultaneously".

Let me know if this satisfy your request.

**Comment by evladutoiu** [comment]
@carstengehling It works flawlessly! That's exactly what me and my colleagues needed. We work as coders but we do a lot of admin stuff and it help to have this feature! 
So far, I haven't found any bugs, i think it can go in production!

Thanks a lot!

**Comment by carstengehling** [comment]
Great - I'll get it merged into master. I'll release a new production version installer some time next week.

**Comment by carstengehling** [comment]
@evladutoiu I've now released an official version containing this feature:

https://github.com/carstengehling/jirastopwatch/releases/tag/1.6.0
