### ISSUE TITLE
Error connecting to JIRA: The underlying connection was closed: Could not establish trust relationship for the SSL/TSL secure channel

### ISSUE THREAD

**Issue by strengthenwhatremains** [carstengehling/jirastopwatch#71]
We use a non public JIRA instance, which has no current certificates at the moment. Would it be possible to bypass/configure the application to bypass the SSL connection?

**Comment by carstengehling** [comment]
Well you could add your own internal root CA certificate as a trusted source. But I do not have a lot of experience with this myself.
