### ISSUE TITLE
Enable resizing of the main window and the vertical scroll bar

### ISSUE THREAD

**Issue by Predhu** [carstengehling/jirastopwatch#73]
Please enable resizing of the window and add a scrollbar (could be optional if you want).
I am using this really useful tool on a small monitor (laptop on dock) and it runs out of space when I am in the unfortunate situation of having lots of items running in parallel.

**Comment by carstengehling** [comment]
It should already do as you suggest. When you add more items than there are room for on the screen, the main window sizes to max available height on the screen, and a vertical scrollbar appears. Like this:

![image](https://cloud.githubusercontent.com/assets/54675/24749341/f9e2fc7e-1ac2-11e7-94f5-b132e336890b.png)

Have you tried this?

**Comment by Predhu** [comment]
Maybe it is because the resolution of the screens I have are different, but on the smaller one, the scrollbar does not appear.

![jirastopwatch](https://cloud.githubusercontent.com/assets/8157621/24750344/be345b56-1ac6-11e7-9100-07fdd247ce89.png)

**Comment by carstengehling** [comment]
Yes - a pull request has actually just been made, that fixes this: https://github.com/carstengehling/jirastopwatch/pull/72

It will be part of next release soon

**Comment by Predhu** [comment]
Thanks!
