### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by lostumbrellas** [carstengehling/jirastopwatch#77]
Unable to connect, and getting these errors in the log:

1/05/2017 2:16:33 PM Try to re-authenticate
1/05/2017 2:16:33 PM Request: https://xxxx.atlassian.net/rest/auth/1/session
1/05/2017 2:16:34 PM Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}

Running version 2.0.1

**Comment by carstengehling** [comment]
Hmmm.... Not to be rude, but it sounds very much like you have entered a wrong username/email or password. Could you try to type both again?

**Comment by lostumbrellas** [comment]
Ha, I agree, sounds like that a lot. But sadly no, have triple checked the username and password.

I was wondering whether it was something to do with the introduction of a single Atlassian Accounts for all their products? https://confluence.atlassian.com/cloud/atlassian-account-for-users-873871199.html

**Comment by carstengehling** [comment]
I haven't heard or read about any changes in this regard when it comes down to the Jira REST API. On a daily basis, I use Jira from a self-hosted installation though, so I wouldn't be the first to experience hiccups like this. I'll try to create a cloud account and test it through.

**Comment by moorereason** [comment]
I'm seeing similar behavior with JIRA Cloud, but after 30s it connects.  Here's the HTTP flow:

```
> 00s  POST /rest/auth/1/session HTTP/1.1
< 00s  HTTP/1.1 500 Internal Server Error

> 00s  GET /rest/auth/1/session HTTP/1.1
< 00s  HTTP/1.1 401 Unauthorized

> 00s  POST /rest/auth/1/session HTTP/1.1
< 00s  HTTP/1.1 500 Internal Server Error

> 00s  GET /rest/auth/1/session HTTP/1.1
< 00s  HTTP/1.1 401 Unauthorized

> 00s  POST /rest/auth/1/session HTTP/1.1
< 00s  HTTP/1.1 500 Internal Server Error

> 30s  GET /rest/auth/1/session HTTP/1.1
< 30s  HTTP/1.1 200 OK
```

**Comment by cpjolly** [comment]
We are also seeing the same issue from all our accounts for our Jira cloud instance. Have Atlassian perhaps changed the authentication requirements ?

**Comment by carstengehling** [comment]
Sounds serious. I will look at this as soon as I can. In the meantime: If there are any developers using StopWatch, who has experienced this, **please help me look into it**, as my time is very limited at the moment.

**Comment by carstengehling** [comment]
I have just tried to make a test Jira cloud site at Atlassian. And I can connect without any problems. Could you please try with the same test-site in your installed Jira StopWatch:

Base URL: https://testgehling2.atlassian.net
Username: carsten@gehling.dk
Password: Simple3ACL

Let me know it it works or not.

**Comment by cpjolly** [comment]
Hi Carsten,

Yes that works !!

My credentials still fail... I will try to create a test account with our Atlassian instance and see if that works.

**Comment by carstengehling** [comment]
@lostumbrellas @moorereason  could you both try the same please?

**Comment by moorereason** [comment]
It's all working fine today (with my own account and the test account above).  I'm guessing Atlassian fixed something.  ?

**Comment by carstengehling** [comment]
Yeah - based on your HTTP flow, it seems that they've got some temporal glitches. I'm glad that's all this was. Closing this issue.

**Comment by carstengehling** [comment]
@cpjolly please let me know about your experience with a new account.

**Comment by cpjolly** [comment]
No matter what I tried, it doesn't work with our credentials and our Jira Cloud instance.

I've logged an issue with Atlassian because I think this is due to the problems they have been having with the Atlassian id SSO service and may not be directly related to Stop Watch

**Comment by ECGroupIT** [comment]
Hi Carsten,

Further to my earlier email to you I have tried your test instance and it works, so there is some issue with my Atlassian credentials.  Also, others in our organisation can connect with StopWatch so it appears to be something to do with my credentials.

I'll raise an issue with Atlassian.

Thanks
Mark

**Comment by carstengehling** [comment]
@cpjolly:

> I've logged an issue with Atlassian because I think this is due to the problems they have been having with the Atlassian id SSO service and may not be directly related to Stop Watch

I haven't heard about this - do you have any further info about it? A link to something from Atlassian perhaps?

**Comment by carstengehling** [comment]
@mark: Thank you for your input. As @cpjolly states, the problems probably originates within Atlassian. But I still would like to make sure that Jira StopWatch is lenient in regard to stuff like this. So I'll see if something can be changed in the components that communicate with the Jira API.

**Comment by lostumbrellas** [comment]
@carstengehling I know you've closed your test cloud account, but here's something I think is relevant. If I go to your login page (https://testgehling2.atlassian.net/login) the username/password form appears. If I go to to the equivalent URL for my cloud account (https://myaccount.atlassian.net/login) I'm redirected to https://id.atlassian.com/login. Atlassian has been gradually migrating accounts over to the Atlassian ID, so I'm wondering if there is something different in the authentication process for those accounts?

**Comment by lostumbrellas** [comment]
Looks like there is a problem with the API: https://jira.atlassian.com/browse/JRACLOUD-66793

**Comment by cpjolly** [comment]
Yep - that fixed it !!!!!!!!!!!!!

- Login to Jira
- go to profile
- see what your username name is
- use that rather than email address

**Comment by ECGroupIT** [comment]
Thank you @lostumbrellas & @cpjolly, that's fixed it for me as well!

**Comment by carstengehling** [comment]
Well done guys, thank you very much! I will update the documentation to include this.

**Comment by carstengehling** [comment]
Documentation now updated - again thank you all for discovering this.

http://jirastopwatch.com/doc/

**Comment by rdewolfe** [comment]
I'm getting a similar error, has anybody gotten this to work using API Tokens?

**Comment by edgolub** [comment]
I have no idea what my JIRA username is, can't find it in my profile. I know what my Nick Name is, as well as the Full Name set there. But I don't think that is the same thing? Where exactly do I find my JIRA username? Because I am using Atlassian ID for JIRA, and can't seem to login with my email and password.

**Comment by josesampergt** [comment]
Hi Carsten, I am having the same issue with not being able to connect, this is reported by several users within the same cloud site, here is the log:

17-Apr-19 7:56:08 AM Request: https://telusglss.atlassian.net/rest/auth/1/session
17-Apr-19 7:56:09 AM Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
17-Apr-19 7:56:09 AM Try to re-authenticate
17-Apr-19 7:56:09 AM Request: https://telusglss.atlassian.net/rest/auth/1/session
17-Apr-19 7:56:09 AM Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
17-Apr-19 7:56:09 AM Request: https://telusglss.atlassian.net/rest/auth/1/session
17-Apr-19 7:56:10 AM Response: Unauthorized - {"errorMessages":["You are not authenticated. Authentication required to perform this operation."],"
17-Apr-19 7:56:10 AM Try to re-authenticate
17-Apr-19 7:56:10 AM Request: https://telusglss.atlassian.net/rest/auth/1/session
17-Apr-19 7:56:10 AM Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
17-Apr-19 7:56:33 AM Request: https://telusglss.atlassian.net/rest/auth/1/session
17-Apr-19 7:56:34 AM Response: Unauthorized - {"errorMessages":["You are not authenticated. Authentication required to perform this operation."],"
17-Apr-19 7:56:34 AM Try to re-authenticate

Did attlasian changed something? can you please help us, thank you!

**Comment by carstengehling** [comment]
Atlassian deprecated the authentication method, that Jira StopWatch used. I've just released a new version today containing a new way to authenticate, using an API token. Get it here https://github.com/carstengehling/jirastopwatch/releases/latest and try it out.
