### ISSUE TITLE
Wider dropdowns for filters

### ISSUE THREAD

**Issue by evladutoiu** [carstengehling/jirastopwatch#8]
Please make the dropdowns fit the largest string! Sometimes the filter names are longer and the box is rather small. Maybe the issues dropdown could be a little longer or maybe wrap the title. Not sure how hard it would be! Would really appreciate this change!

**Comment by carstengehling** [comment]
Sure thing - I'll have a look at this :-)

**Comment by carstengehling** [comment]
Just to be sure - we are talking about the drop-down box in the bottom of the window - right? The other drop-down boxes are already as wide as the parent window.

**Comment by evladutoiu** [comment]
Yeah! And also on the other dropdowns, is it possible to wrap the issue
title?

**Comment by carstengehling** [comment]
Maybe - I implement my own drawing code on the dropdown already. So it might be possible

**Comment by carstengehling** [comment]
This request is turning out to be more difficult than I first thought. I have trouble making the dropdown area becoming the right height, when one or more (but not all) summary are wrapped.

I don't know if you are proficient in C# and WinForms yourself, but I've made a feature-branch so that you or anyone else can pitch in: https://github.com/carstengehling/jirastopwatch/tree/cbjirawordwrap

**Comment by evladutoiu** [comment]
@carstengehling 
Personally, I don't have that kind of knowledge, but maybe someone else will be able to look at it! 
I appreciate your time and effort on this! You make my life so much easier with this tool!

**Comment by carstengehling** [comment]
Well I'm happy that I do. The idea for the application also came from trying to make things easier for myself. So I'm glad when other people get the same result.

**Comment by carstengehling** [comment]
@evladutoiu I haven't been able to make the word-wrap work, so only the wider dropdown in the bottom has been included in the latest release:

https://github.com/carstengehling/jirastopwatch/releases/tag/1.6.0
