### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Javiez** [carstengehling/jirastopwatch#80]
Hi,

After successfully setup the first time and tested the JIRA stopwatch, I am not unable to connect to my JIRA cloud account. It keeps indicating unauthorized connection but I have no issue to login online. What could be the problem?

From the log.
19/05/17 9:35:31 AM Request: https://axaarit.atlassian.net/rest/auth/1/session
19/05/17 9:35:31 AM Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
19/05/17 9:35:31 AM Try to re-authenticate

**Comment by carstengehling** [comment]
Please have a look at this issue: https://github.com/carstengehling/jirastopwatch/issues/77

It seems that Atlassian might have some temporal problems when doing login to their Cloud API. I know that other people in that thread have contacted Atlassian support to find out what is going on. Maybe you could try the same. As far as we have found out so far, the error is not in Jira StopWatch. But I would very much like to hear, what Atlassian might tell you.

**Comment by carstengehling** [comment]
The source of the problem has now been discovered - please look at the Basic Setup section on Jira StopWatch's documentation site: http://jirastopwatch.com/doc/
