### ISSUE TITLE
Display of disrupting issue state change

### ISSUE THREAD

**Issue by joanis** [carstengehling/jirastopwatch#81]
A colleague suggested that we should perhaps remove items which were closed by someone else.

I'll suggest something I consider a bit more userfriendly. How about an indicator somewhere in the IssueControl which would warn the user when something "significant" happened with the issue? Could either be an indicator that lights up with precisions found in a tooltip, or different icons appearing depending on the actual event.

We'd like to ignore description changes, estimate changes, etc... but display something when an issue is
- closed
- moved out of the scope of the current sprint
- assigned to someone else
- (help me think of other events which would necessarily require attention before (or instead of) continuing to work on an issue)

Somewhat related to #75 (but more general?)

I wouldn't mind working on it.

**Comment by carstengehling** [comment]
It's important to understand, that Jira StopWatch was never originally intented to be "the entrypoint dashboard to Jira", but simply a way for a single user to a) get an overview of the tasks currently at hand and b) track the time spent on each of these tasks.

That said, I'm open for good suggestions. Give it a shot and let me see, how it might work.
