### ISSUE TITLE
Display parent issue numbers and summaries

### ISSUE THREAD

**Issue by joanis** [carstengehling/jirastopwatch#82]
I often end up adding details in task summaries so that their displayed description (in Jira StopWatch) is the least bit telling. Instead of having tasks titled "Merge code" or "Analysis" for example, which don't give any hint of what it's about, I'd trade a little space against more information about the context of a task. I thought an option could be added such as "Display parent summaries" and let users decide whether to
- keep things as they are (feature disabled),
- show info about the immediate parent (only one level up, if any),
- or show all parents (e.g. task itself, user story, and epic).

Not sure about the complexity of this (mainly in term of possible issue structures in JIRA itself, and associated queries) but it doesn't sound like too much work.

Wouldn't mind working on it.

**Comment by carstengehling** [comment]
Optionally display parent task would be quite useful. If I'm not mistaken, the info is already available in the API call that retrieves the issue summary - I just don't map it to any attribute at the moment. It could be displayed like this in the summary line:

Parent issue summary / actual issue summary

But I agree that it should be optional from the settings. For some this might not be useful.
