### ISSUE TITLE
No connection since Jira with G-Suite integration

### ISSUE THREAD

**Issue by ljay79** [carstengehling/jirastopwatch#84]
Hi.
Since Atlassian Jira integrated G-Suite support and migrated all their Atlassian accounts, i am unable to use JiraStopWatch on Win10 anymore.

Its simply not connecting, while i was using it perfectly fine long time until then.
I am Jira and G-Suite admin, login details are correct - same as before were it was working.

using Jira OnDemand

Error Log, only shows:
```
12.06.2017 09:12:50 Request: https://*****.atlassian.net/rest/auth/1/session
12.06.2017 09:12:50 Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
12.06.2017 09:12:50 Try to re-authenticate
12.06.2017 09:12:50 Request: https://*****.atlassian.net/rest/auth/1/session
12.06.2017 09:12:51 Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
12.06.2017 09:12:51 Request: https://*****.atlassian.net/rest/auth/1/session
12.06.2017 09:12:51 Response: Unauthorized - {"errorMessages":["You are not authenticated. Authentication required to perform this operation."],"
12.06.2017 09:12:51 Try to re-authenticate
12.06.2017 09:12:51 Request: https://*****.atlassian.net/rest/auth/1/session
12.06.2017 09:12:51 Response: Unauthorized - {"errorMessages":["Login failed"],"errors":{}}
```

**Comment by carstengehling** [comment]
Please have a look on Jira StopWatch' documentation site, especially the section "Basic setup" 

http://jirastopwatch.com/doc/#basicsetup

See if that helps you.

**Comment by ljay79** [comment]
Awesome, using username instead of email address now since G-Suite integration works.
Thx
