### ISSUE TITLE
Can't connect to Jira server, link start tag does not match end of head tag.

### ISSUE THREAD

**Issue by AreDubya** [carstengehling/jirastopwatch#85]
I'm trying to get setup, but when trying to connect I get the error in the screenshot 
<img width="360" alt="jiratimerissue" src="https://user-images.githubusercontent.com/520744/27047105-19e8208c-4f64-11e7-955a-cedc10e0ece1.png">

I'm running Windows 10, build 14393.1198.
What can I do to sort this out?

**Comment by AreDubya** [comment]
Doh! Actually, this was caused by a typo in the url, which I noticed when I checked the log file. My bad, connected now.

**Comment by carstengehling** [comment]
I'm glad you figured it out. Hope you'll get good use of Jira StopWatch!
