### ISSUE TITLE
[Feature] Sortable List

### ISSUE THREAD

**Issue by AlirezaAkbarix** [carstengehling/jirastopwatch#87]
Thanks for your nice job, I was wonder if I could sort the inserted list via drag & drop.

**Comment by carstengehling** [comment]
Thank you. You cannot sort the list with drag and drop. I also have a hard time seeing the need for this? It's just for time-recording, the order of the list is not really important?

**Comment by AlirezaAkbarix** [comment]
What about sending all time logs via one button?

**Comment by mcascone** [comment]
@AlirezaAkbarix #150
