### ISSUE TITLE
TLSv1.2

### ISSUE THREAD

**Issue by swainr** [carstengehling/jirastopwatch#88]
Wireshark shows that the client is using TLSv1. Can it be updated to use TLSv1.2? Otherwise it fails to connect when the server hosting JIRA rejects older SSL protocols.

**Comment by slarti-b** [comment]
Oh, yes!  I know my company will shortly stop supporting older SSL protocols (it's a PCI DSS compliance issue - I know Jira doesn't contain card data, but I think we are basically turning it off everywhere).  And I doubt we are alone in that.

**Comment by carstengehling** [comment]
Well StopWatch uses RestSharp for all HTTP(S) communication. So it really depends on whether RestSharp can use TLS 1.2 I'll investigate.

**Comment by carstengehling** [comment]
I've looked at this, and as far as I understand (see link below) I can configure which protocols, that the built-in HTTPS may use: https://stackoverflow.com/questions/30409048/restsharp-tls-1-1

If I make a branch for experimenting with this, will you be able to test it for me? I have no access to Jira servers with this level of protection.

**Comment by carstengehling** [comment]
Seems to be a very simple thing to do, once you know how. ;-) @swainr could you grab the tls12 branch and test this? I can build a binary for you, if you don't have Visual Studio.

**Comment by slarti-b** [comment]
I grabbed that branch and did a very quick test (connect and change one issue ID only).  Seems to work.  I was using Wireshark (as @swainr did): with the new version I only see TCP and TVLv1.2 connections; with the old one it's all TCP and TVLSv1.  

We haven't turned off the old SSL versions yet, so I can't verify that.  But we do support them, so neither can I verify that the new version still works against a server without TLSv1.2 - but I guess you have done that already @carstengehling ?

**Comment by swainr** [comment]
Sorry for the delay, I forgot the notifications for GitHub were being sent to an email I don't always check. I pulled down the **tls12** branch, built it and tested. Everything looks right now in Wireshark as @slarti-b reported with it now using TLSv1.2 where it shows TLSv1 for the current release. I also toggled the security settings on our JIRA server to test both builds under more permissive SSL settings and with rejecting all but TLSv1.2 connections and all was as expected. Thanks for such a fast solution @carstengehling !

**Comment by swainr** [comment]
A thought occurred to me when looking at the changes in your commit that since it explicitly called out TLSv1.1 and 1.2, it could be a breaking change if someone only allows TLSv1 (which is what the client uses in the current release). I changed my JIRA server to accept only one SSL protocol at a time and cycled through them. 

It did fail to connect when my server was set to only accept TLSv1. Adding that to your line 37 changes in Program.cs :
`                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;`
and rebuilding I tested and verified that the client successfully connects to a JIRA server that is requiring any of the three "current" SSL protocols. The only way it should reject is if someone is only accepting SSLv3, but I would hope that is not something anyone is doing... (and if you wanted it could be added to the list as well).

@carstengehling - Is there anything else you'd like me to test or should I mark this issue as closed? Also do you plan on merging this into master and putting out an new release version, or should I distribute the build from this branch internally?

**Comment by carstengehling** [comment]
I'll merge the branch into master and then make a new release in the next few days. So if you're all satisfied, I will close the issue now.
