### ISSUE TITLE
Daily connection issue

### ISSUE THREAD

**Issue by ECGroupIT** [carstengehling/jirastopwatch#89]
Hi,

I have to reset my JIRA password every day in order to get the JIRA StopWatch (v2.0.1) app to connect to my JIRA cloud instance.  I don't have to change the password, just reenter it into JIRA. So daily what I do to get the system working is:

1. Log in to JIRA cloud.
2. Launch JIRA StopWatch. This shows a status of 'Not connected'
3. Browse to my JIRA profile, select change password, enter the current password, enter the current password as my new password (i.e. do not change the password).
4. Select the JIRA StopWatch configure cog to open the settings dialogue, select the OK button to close the dialogue (without changing anything).
5. JIRA StopWatch connects and shows a status of 'Connected'

What do you suggest I do to resolve this issue?

Thanks
Mark

**Comment by carstengehling** [comment]
You are using Jira Cloud. Have a look at this section in the documentation, that addresses this.http://jirastopwatch.com/doc/#basicsetup

Let me know if this helps.

**Comment by ECGroupIT** [comment]
Yes, as stated in my original comments for this issue I am using JIRA cloud.

I have already reviewed the linked document, but it does not address the issue I am experiencing as outlined in my original comment - which happened again this morning. As originally stated, I can connect to JIRA using the JIRA StopWatch app (I am connected now as we speak), the issue is the steps I have to go through every morning to get the app to connect.

Please review the points I originally posted and let me know if any of those need clarification.

Thanks
Mark

**Comment by carstengehling** [comment]
What I first need to know is: Do you use your e-mail address or your username in Jira StopWatch?  It might be significant.

**Comment by ECGroupIT** [comment]
I have tried both, and am now using my user name.

**Comment by carstengehling** [comment]
That is very strange, I must admit that I haven't heard about this behavior before. Since you say that this only started a week ago, and due to you having to do a fix in your Jira account, I'm quite sure, that the problem originates in your Jira Cloud instance. 

Do you maybe have some other script, that tries to log into your account with a wrong password, and thereby locks your account?

**Comment by carstengehling** [comment]
Maybe you could try to log an issue on Atlassian's support, detailing the steps needed to make login to work. Jira StopWatch simply uses the authentication schemes described on the Cloud Rest API documentation page: https://docs.atlassian.com/jira/REST/cloud/#auth/1/session

**Comment by carstengehling** [comment]
@ECGroupIT have you found a resolution for this)

**Comment by ECGroupIT** [comment]
Hi Carsten,

Thanks for looking into this.  Like you I think that this is likely some sort of issue with my cloud account.  I do not have any other scripts trying to connect to my account as far as I am aware.  Having said that, I'm unaware of any way to monitor this on the JIRA cloud - I'll raise a ticket with Atlassian to check this.  Also, I am not getting locked out of JIRA itself, it is just StopWatch that can't connect until I reset the password to the same password.

All very strange. 

I'll pursue this with Atlassian and see what they can find.

Thanks
Mark
