### ISSUE TITLE
Issue dropdowns are not updated when I change the filter

### ISSUE THREAD

**Issue by dhanak** [carstengehling/jirastopwatch#9]
I have multiple filters, but only one of them (let's call this "A") causes StopWatch to update its issue dropdown list. The others have no effect at all. Furthermore, if I start up with "A", the issue list is properly initialized, but if StopWatch is started with any of the other filters selected, then the issue lists are empty. Then when I switch to "A", the lists are updated correctly, but when I switch to another filter, nothing happens, the lists remain as they are. Apparently, filter "A" is the first in the list, but this might have nothing to do with the issue. Do you have some sort of logfile where I can check for errors?

**Comment by carstengehling** [comment]
No I don't log anything with the application. I've tried to reproduce it locally, but in my installation everything works as it should.

Jira StopWatch communicates with Jira through Jira's Rest API over the HTTP protocol. So you could try to install Fiddler and watch what is sent back and forth. http://www.telerik.com/fiddler

**Comment by carstengehling** [comment]
@dhanak did you find out anything?

**Comment by dhanak** [comment]
Sorry, I didn't have time yet to investigate the issue. My main concern is
that our JIRA server is usually reached via https, and I am not sure it is
accessible via regular http at all. But I will check and keep you posted.

Thanks for the quick response anyway!

**Comment by carstengehling** [comment]
Yeah that might make it difficult to use Fiddler. Let me know if you don't figure it out.

**Comment by danteblitz123** [comment]
I am experiencing the same thing. 

I can connect to my Jira instance but all dropdowns are empty. If i Type an issue is I get nothing. However I f i restart the Stopwatch app then the issue IDs that I previously types are recalled but now I can see the issue description. 

However I cannot submit any work logs back to Jira. The button is disabled.

**Comment by carstengehling** [comment]
@danteblitz123 would it be possible for you to look at the communication between StopWatch and Jira through Fiddler?

**Comment by carstengehling** [comment]
@danteblitz123 it sounds a bit like, that you are not logged in. Jira installations can easily have anonymous read-only access to issues, which could explain why the description is shown, but that you cannot post worklog. Have a look in the bottom left corner - does it say "Connected" or "Not connected"?
