### ISSUE TITLE
Auto default to one minute if time spent is less than a minute

### ISSUE THREAD

**Issue by gsmith523** [carstengehling/jirastopwatch#91]
Occasionally my team spends less than a minute on a project (entering a note, etc), but they have to wait until Jira Stopwatch registers that a minute has passed to push to Jira.  Is there a way to have the application automatically round to the next whole minute (or default to 1 minute is less than a minute is logged)?

**Comment by slarti-b** [comment]
I'd vote for always rounding up.  i think it fits how time reporting works in most places best (for my actual time reporting (in another tool) I round up to next 15 min interval - I know some people do per minute (maybe not devs, I know some lawyers do), but I doubt anyone does per second :)

**Comment by carstengehling** [comment]
I think it is a great idea, so @gsmith523 feel free to submit a pull request. My own time is unfortunately very limited at the moment, which will probably not change until around november.

**Comment by gsmith523** [comment]
Sorry, I am not familiar with the process.  I looked at adding a pull request but am not sure which options to choose.

**Comment by carstengehling** [comment]
The easiest way is:

1. Fork the repository to get your own copy into https://github.com/gsmith523/jirastopwatch
2. Work on this copy
3. Create a pull request with the changes - described here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

For a description on the entire flow, read https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by carstengehling** [comment]
I've just made it myself. :-)
