### ISSUE TITLE
add user inactivity tracking

### ISSUE THREAD

**Issue by rvit34** [carstengehling/jirastopwatch#92]
It would be a nice feature if you add the user inactivity tracking.
When an user move away from its computer and forget to stop the timer need to stop it automatically. (inactivity time should be configurable).
When an user come back need to show the popup window with some options: continue working to an issue, cancel, edit time (in case that inactivity definition was incorrect)
Look at how it works in worklog assistant for example.

**Comment by carstengehling** [comment]
Not sure it's a feature I'll ever use, since I'm also required to track time used in meetings. But feel free to make it and submit a pull request, and I will add it.

**Comment by rvit34** [comment]
You probably already had the similar feature but it seems not working for me. You call it "Pause timer on session lock". As I understand correctlly the program timer should stop when my displays goes off/my pc goes to sleep mode. That's correct? I set sleep mode after 2mins of user inactivity in my win7 machine. After 2mins my pc went to sleep mode. I waited a few minutes and returned back but timer was running all that time. In program settings I set "pause and resume on unlock". 
Anyway In my opinion it's not a good idea to bind pause/resume timer on system modes or something similar. Imho it's much more better to define user inactivity in you own way. 
As you need to track some meetings its feature might be optional.
I am not such familiar with your code yet so I cannot do it right now and quickly.
So, if this feature also seems usefull for you, please add it.

**Comment by slarti-b** [comment]
If the computer actually sleeps I guess the timer stops anyway?  Question is, does it _lock_ (do you have to enter your password again when you wake it up) or just turn the screen off?

If you do a feature with an inactivity pause, a nice option might be that it still tracks the time (but as "inactive time" and gives you the option to count it or not when you become active again.  So, if I work 10 minutes then wander away for 20 minutes, when I come back it says "You were away 20 mins, should this count as time worked on this issue? Yes (timer continues from 30) or No (time continues from 10)"

**Comment by rvit34** [comment]
No. Just turn my screen off. That's why the timer continued counting.
Yeah, you decribed a very good use case. 
If we or someone else implement that it wil be very handy addition.

**Comment by carstengehling** [comment]
Sleep mode is not the same as locking your computer. In Jira StopWatch context, sleep mode will behave like the application still running.

If you want this changed, you are very welcome to build it and submit a pull-request.
