### ISSUE TITLE
Suggestion: Refresh functionality

### ISSUE THREAD

**Issue by slarti-b** [carstengehling/jirastopwatch#93]
I still sometimes (when waking up the computer, changing VPNs, etc.) get a situation where some or most of the issue names are missing.  Would it be an idea to add a button/keyboard short-cut that simply cycles through all issues and updates the known info on them.  A kind of "refresh page" but it doesn't affect the actual timers, just the issue info.

**Comment by carstengehling** [comment]
I've just released a new version, that include the bugfix for disappearing issue summaries. Have a look first, if this helps with your situation.

**Comment by slarti-b** [comment]
Will see if it helps, thanks

**Comment by slarti-b** [comment]
Haven't experienced this for a while so looks like the latest fix works
