### ISSUE TITLE
Feature request: New setting - "Possible state changes when pressing pause"

### ISSUE THREAD

**Issue by BagumEpmak** [carstengehling/jirastopwatch#94]
It is usefull to have only one "in progress" issue.

**Comment by carstengehling** [comment]
Thank you for your input. However, Jira StopWatch is not really made to keep track of, which issues you currently have at any specific status. It is mainly to track what you've been using your time on during your work-day.

**Comment by carstengehling** [comment]
IMHO this results in an unnecessarily huge amount of state changes, which will flood watcher's e-mail inbox. But if this is really important to you, you are welcome to build it and submit a pull request.
